import { AllergenId, Language } from '../types';

interface AllergenImages {
  examples: string[];
  description: Record<Language, string>;
  warning?: Record<Language, string>;
}

export const ALLERGEN_IMAGES: Record<AllergenId, AllergenImages> = {
  gluten: {
    examples: ['🍞', '🥖', '🍕', '🍝', '🥐', '🍰', '🥧', '🍪'],
    description: {
      it: 'Pane, pasta, pizza, dolci, biscotti, cereali',
      en: 'Bread, pasta, pizza, cakes, cookies, cereals',
      fr: 'Pain, pâtes, pizza, gâteaux, biscuits, céréales',
      de: 'Brot, Nudeln, Pizza, Kuchen, Kekse, Getreide',
      es: 'Pan, pasta, pizza, pasteles, galletas, cereales',
      pt: 'Pão, massa, pizza, bolos, bolachas, cereais',
      nl: 'Brood, pasta, pizza, gebak, koekjes, granen',
      pl: 'Chleb, makaron, pizza, ciasta, ciastka, zboża',
      ru: 'Хлеб, макароны, пицца, торты, печенье, хлопья',
      sv: 'Bröd, pasta, pizza, kakor, kex, flingor',
      zh: '面包、意面、披萨、蛋糕、饼干、谷物',
      ja: 'パン、パスタ、ピザ、ケーキ、クッキー、シリアル',
      ko: '빵, 파스타, 피자, 케이크, 쿠키, 시리얼',
      th: 'ขนมปัง พาสต้า พิซซ่า เค้ก คุกกี้ ธัญพืช',
      ar: 'خبز، معكرونة، بيتزا، كعك، بسكويت، حبوب',
    },
    warning: {
      it: '⚠️ Attenzione: la salsa di soia può contenere glutine',
      en: '⚠️ Warning: soy sauce may contain gluten',
      fr: '⚠️ Attention : la sauce soja peut contenir du gluten',
      de: '⚠️ Achtung: Sojasauce kann Gluten enthalten',
      es: '⚠️ Atención: la salsa de soja puede contener gluten',
      pt: '⚠️ Atenção: o molho de soja pode conter glúten',
      nl: '⚠️ Waarschuwing: sojasaus kan gluten bevatten',
      pl: '⚠️ Uwaga: sos sojowy może zawierać gluten',
      ru: '⚠️ Внимание: соевый соус может содержать глютен',
      sv: '⚠️ Varning: sojasås kan innehålla gluten',
      zh: '⚠️ 注意：酱油可能含有麸质',
      ja: '⚠️ 注意：醤油にはグルテンが含まれている場合があります',
      ko: '⚠️ 주의: 간장에는 글루텐이 포함될 수 있습니다',
      th: '⚠️ คำเตือน: ซอสถั่วเหลืองอาจมีกลูเตน',
      ar: '⚠️ تحذير: قد تحتوي صلصة الصويا على الغلوتين',
    },
  },
  crustaceans: {
    examples: ['🦐', '🦞', '🦀', '🍤'],
    description: {
      it: 'Gamberi, aragoste, granchi, scampi',
      en: 'Shrimp, lobster, crab, prawns',
      fr: 'Crevettes, homard, crabe, langoustines',
      de: 'Garnelen, Hummer, Krabben, Scampi',
      es: 'Gambas, langosta, cangrejo, langostinos',
      pt: 'Camarões, lagosta, caranguejo, lagostins',
      nl: 'Garnalen, kreeft, krab, scampi',
      pl: 'Krewetki, homary, kraby, langustynki',
      ru: 'Креветки, лобстеры, крабы, лангустины',
      sv: 'Räkor, hummer, krabba, havskräfta',
      zh: '虾、龙虾、螃蟹、明虾',
      ja: 'エビ、ロブスター、カニ、車海老',
      ko: '새우, 랍스터, 게, 대하',
      th: 'กุ้ง ล็อบสเตอร์ ปู กุ้งใหญ่',
      ar: 'جمبري، كركند، سلطعون، قريدس',
    },
  },
  eggs: {
    examples: ['🥚', '🍳', '🍰', '🥮', '🍮', '🥞'],
    description: {
      it: 'Uova, frittate, dolci, maionese, pasta fresca',
      en: 'Eggs, omelettes, cakes, mayonnaise, fresh pasta',
      fr: 'Œufs, omelettes, gâteaux, mayonnaise, pâtes fraîches',
      de: 'Eier, Omeletts, Kuchen, Mayonnaise, frische Nudeln',
      es: 'Huevos, tortillas, pasteles, mayonesa, pasta fresca',
      pt: 'Ovos, omeletes, bolos, maionese, massa fresca',
      nl: 'Eieren, omeletten, gebak, mayonaise, verse pasta',
      pl: 'Jajka, omlety, ciasta, majonez, świeży makaron',
      ru: 'Яйца, омлеты, торты, майонез, свежая паста',
      sv: 'Ägg, omeletter, tårtor, majonnäs, färsk pasta',
      zh: '鸡蛋、煎蛋、蛋糕、蛋黄酱、新鲜意面',
      ja: '卵、オムレツ、ケーキ、マヨネーズ、生パスタ',
      ko: '달걀, 오믈렛, 케이크, 마요네즈, 생면',
      th: 'ไข่ ออมเล็ต เค้ก มายองเนส พาสต้าสด',
      ar: 'بيض، عجة، كعك، مايونيز، معكرونة طازجة',
    },
  },
  fish: {
    examples: ['🐟', '🐠', '🐡', '🍣', '🍥'],
    description: {
      it: 'Pesce, sushi, salse di pesce, brodi',
      en: 'Fish, sushi, fish sauces, broths',
      fr: 'Poisson, sushi, sauces de poisson, bouillons',
      de: 'Fisch, Sushi, Fischsaucen, Brühen',
      es: 'Pescado, sushi, salsas de pescado, caldos',
      pt: 'Peixe, sushi, molhos de peixe, caldos',
      nl: 'Vis, sushi, vissauzen, bouillon',
      pl: 'Ryby, sushi, sosy rybne, buliony',
      ru: 'Рыба, суши, рыбные соусы, бульоны',
      sv: 'Fisk, sushi, fisksåser, buljonger',
      zh: '鱼、寿司、鱼酱、高汤',
      ja: '魚、寿司、魚醤、出汁',
      ko: '생선, 초밥, 어장, 육수',
      th: 'ปลา ซูชิ น้ำปลา น้ำซุป',
      ar: 'سمك، سوشي، صلصات سمك، مرق',
    },
  },
  peanuts: {
    examples: ['🥜', '🍫', '🥧', '🍪'],
    description: {
      it: 'Arachidi, burro di arachidi, snack, dolci',
      en: 'Peanuts, peanut butter, snacks, desserts',
      fr: 'Arachides, beurre de cacahuète, snacks, desserts',
      de: 'Erdnüsse, Erdnussbutter, Snacks, Desserts',
      es: 'Cacahuetes, mantequilla de cacahuete, aperitivos, postres',
      pt: 'Amendoins, manteiga de amendoim, snacks, sobremesas',
      nl: 'Pinda\'s, pindakaas, snacks, desserts',
      pl: 'Orzeszki ziemne, masło orzechowe, przekąski, desery',
      ru: 'Арахис, арахисовое масло, закуски, десерты',
      sv: 'Jordnötter, jordnötssmör, snacks, desserter',
      zh: '花生、花生酱、零食、甜点',
      ja: 'ピーナッツ、ピーナッツバター、スナック、デザート',
      ko: '땅콩, 땅콩버터, 스낵, 디저트',
      th: 'ถั่วลิสง เนยถั่ว ขนมขบเคี้ยว ของหวาน',
      ar: 'فول سوداني، زبدة فول سوداني، وجبات خفيفة، حلويات',
    },
  },
  soy: {
    examples: ['🫘', '🍶', '🥡', '🍜'],
    description: {
      it: 'Tofu, salsa di soia, latte di soia, edamame',
      en: 'Tofu, soy sauce, soy milk, edamame',
      fr: 'Tofu, sauce soja, lait de soja, edamame',
      de: 'Tofu, Sojasauce, Sojamilch, Edamame',
      es: 'Tofu, salsa de soja, leche de soja, edamame',
      pt: 'Tofu, molho de soja, leite de soja, edamame',
      nl: 'Tofu, sojasaus, sojamelk, edamame',
      pl: 'Tofu, sos sojowy, mleko sojowe, edamame',
      ru: 'Тофу, соевый соус, соевое молоко, эдамаме',
      sv: 'Tofu, sojasås, sojamjölk, edamame',
      zh: '豆腐、酱油、豆浆、毛豆',
      ja: '豆腐、醤油、豆乳、枝豆',
      ko: '두부, 간장, 두유, 에다마메',
      th: 'เต้าหู้ ซอสถั่วเหลือง นมถั่วเหลือง ถั่วแระญี่ปุ่น',
      ar: 'توفو، صلصة صويا، حليب صويا، إدامامي',
    },
  },
  milk: {
    examples: ['🥛', '🧀', '🧈', '🍦', '🍨', '🎂'],
    description: {
      it: 'Latte, formaggi, burro, gelato, panna',
      en: 'Milk, cheese, butter, ice cream, cream',
      fr: 'Lait, fromages, beurre, glace, crème',
      de: 'Milch, Käse, Butter, Eiscreme, Sahne',
      es: 'Leche, quesos, mantequilla, helado, nata',
      pt: 'Leite, queijos, manteiga, gelado, natas',
      nl: 'Melk, kaas, boter, ijs, room',
      pl: 'Mleko, sery, masło, lody, śmietana',
      ru: 'Молоко, сыры, масло, мороженое, сливки',
      sv: 'Mjölk, ost, smör, glass, grädde',
      zh: '牛奶、奶酪、黄油、冰淇淋、奶油',
      ja: '牛乳、チーズ、バター、アイスクリーム、クリーム',
      ko: '우유, 치즈, 버터, 아이스크림, 크림',
      th: 'นม ชีส เนย ไอศกรีม ครีม',
      ar: 'حليب، جبن، زبدة، آيس كريم، كريمة',
    },
  },
  nuts: {
    examples: ['🌰', '🥜', '🍫', '🍰', '🥧'],
    description: {
      it: 'Noci, mandorle, nocciole, pistacchi, anacardi',
      en: 'Walnuts, almonds, hazelnuts, pistachios, cashews',
      fr: 'Noix, amandes, noisettes, pistaches, noix de cajou',
      de: 'Walnüsse, Mandeln, Haselnüsse, Pistazien, Cashews',
      es: 'Nueces, almendras, avellanas, pistachos, anacardos',
      pt: 'Nozes, amêndoas, avelãs, pistácios, cajus',
      nl: 'Walnoten, amandelen, hazelnoten, pistachenoten, cashewnoten',
      pl: 'Orzechy włoskie, migdały, orzechy laskowe, pistacje, orzechy nerkowca',
      ru: 'Грецкие орехи, миндаль, фундук, фисташки, кешью',
      sv: 'Valnötter, mandlar, hasselnötter, pistaschnötter, cashewnötter',
      zh: '核桃、杏仁、榛子、开心果、腰果',
      ja: 'クルミ、アーモンド、ヘーゼルナッツ、ピスタチオ、カシューナッツ',
      ko: '호두, 아몬드, 헤이즐넛, 피스타치오, 캐슈넛',
      th: 'วอลนัท อัลมอนด์ เฮเซลนัท พิสทาชิโอ มะม่วงหิมพานต์',
      ar: 'جوز، لوز، بندق، فستق، كاجو',
    },
  },
  celery: {
    examples: ['🥬', '🥗', '🍲', '🥣'],
    description: {
      it: 'Sedano, insalate, zuppe, brodi vegetali',
      en: 'Celery, salads, soups, vegetable broths',
      fr: 'Céleri, salades, soupes, bouillons de légumes',
      de: 'Sellerie, Salate, Suppen, Gemüsebrühen',
      es: 'Apio, ensaladas, sopas, caldos de verduras',
      pt: 'Aipo, saladas, sopas, caldos de legumes',
      nl: 'Selderij, salades, soepen, groentebouillon',
      pl: 'Seler, sałatki, zupy, buliony warzywne',
      ru: 'Сельдерей, салаты, супы, овощные бульоны',
      sv: 'Selleri, sallader, soppor, grönsaksbuljonger',
      zh: '芹菜、沙拉、汤、蔬菜高汤',
      ja: 'セロリ、サラダ、スープ、野菜ブイヨン',
      ko: '셀러리, 샐러드, 수프, 채소 육수',
      th: 'ขึ้นฉ่าย สลัด ซุป น้ำซุปผัก',
      ar: 'كرفس، سلطات، شوربات، مرق خضار',
    },
  },
  mustard: {
    examples: ['🌭', '🥪', '🍔', '🥗'],
    description: {
      it: 'Senape, salse, condimenti, marinate',
      en: 'Mustard, sauces, dressings, marinades',
      fr: 'Moutarde, sauces, vinaigrettes, marinades',
      de: 'Senf, Saucen, Dressings, Marinaden',
      es: 'Mostaza, salsas, aderezos, marinadas',
      pt: 'Mostarda, molhos, temperos, marinadas',
      nl: 'Mosterd, sauzen, dressings, marinades',
      pl: 'Gorczyca, sosy, dressingi, marynaty',
      ru: 'Горчица, соусы, заправки, маринады',
      sv: 'Senap, såser, dressingar, marinader',
      zh: '芥末、酱料、调味汁、腌料',
      ja: 'マスタード、ソース、ドレッシング、マリネ',
      ko: '겨자, 소스, 드레싱, 마리네이드',
      th: 'มัสตาร์ด ซอส น้ำสลัด น้ำหมัก',
      ar: 'خردل، صلصات، تتبيلات، ماريناد',
    },
  },
  sesame: {
    examples: ['🥯', '🍞', '🥗', '🍜'],
    description: {
      it: 'Semi di sesamo, olio di sesamo, hummus, pane',
      en: 'Sesame seeds, sesame oil, hummus, bread',
      fr: 'Graines de sésame, huile de sésame, houmous, pain',
      de: 'Sesamsamen, Sesamöl, Hummus, Brot',
      es: 'Semillas de sésamo, aceite de sésamo, hummus, pan',
      pt: 'Sementes de sésamo, óleo de sésamo, hummus, pão',
      nl: 'Sesamzaad, sesamolie, hummus, brood',
      pl: 'Nasiona sezamu, olej sezamowy, hummus, chleb',
      ru: 'Семена кунжута, кунжутное масло, хумус, хлеб',
      sv: 'Sesamfrön, sesamolja, hummus, bröd',
      zh: '芝麻、芝麻油、鹰嘴豆泥、面包',
      ja: 'ゴマ、ごま油、フムス、パン',
      ko: '참깨, 참기름, 후무스, 빵',
      th: 'งา น้ำมันงา ฮัมมัส ขนมปัง',
      ar: 'بذور سمسم، زيت سمسم، حمص، خبز',
    },
  },
  sulfites: {
    examples: ['🍷', '🍺', '🥗', '🍟'],
    description: {
      it: 'Vino, birra, frutta secca, patatine',
      en: 'Wine, beer, dried fruit, chips',
      fr: 'Vin, bière, fruits secs, chips',
      de: 'Wein, Bier, Trockenfrüchte, Chips',
      es: 'Vino, cerveza, fruta seca, patatas fritas',
      pt: 'Vinho, cerveja, fruta seca, batatas fritas',
      nl: 'Wijn, bier, gedroogd fruit, chips',
      pl: 'Wino, piwo, suszone owoce, chipsy',
      ru: 'Вино, пиво, сухофрукты, чипсы',
      sv: 'Vin, öl, torkad frukt, chips',
      zh: '葡萄酒、啤酒、干果、薯片',
      ja: 'ワイン、ビール、ドライフルーツ、チップス',
      ko: '와인, 맥주, 건과일, 칩',
      th: 'ไวน์ เบียร์ ผลไม้แห้ง มันฝรั่งทอด',
      ar: 'نبيذ، بيرة، فواكه مجففة، رقائق',
    },
  },
  lupin: {
    examples: ['🫘', '🍞', '🥧', '🍝'],
    description: {
      it: 'Farina di lupini, pane, pasta, snack',
      en: 'Lupin flour, bread, pasta, snacks',
      fr: 'Farine de lupin, pain, pâtes, snacks',
      de: 'Lupinenmehl, Brot, Nudeln, Snacks',
      es: 'Harina de altramuz, pan, pasta, aperitivos',
      pt: 'Farinha de tremoço, pão, massa, snacks',
      nl: 'Lupinemeel, brood, pasta, snacks',
      pl: 'Mąka łubinowa, chleb, makaron, przekąski',
      ru: 'Люпиновая мука, хлеб, паста, закуски',
      sv: 'Lupinmjöl, bröd, pasta, snacks',
      zh: '羽扇豆粉、面包、意面、零食',
      ja: 'ルピナス粉、パン、パスタ、スナック',
      ko: '루핀 가루, 빵, 파스타, 스낵',
      th: 'แป้งลูปิน ขนมปัง พาสต้า ขนมขบเคี้ยว',
      ar: 'دقيق ترمس، خبز، معكرونة، وجبات خفيفة',
    },
  },
  mollusks: {
    examples: ['🦪', '🦑', '🐙', '🥘'],
    description: {
      it: 'Cozze, vongole, ostriche, calamari, polpo',
      en: 'Mussels, clams, oysters, squid, octopus',
      fr: 'Moules, palourdes, huîtres, calamars, poulpe',
      de: 'Muscheln, Venusmuscheln, Austern, Tintenfisch, Oktopus',
      es: 'Mejillones, almejas, ostras, calamares, pulpo',
      pt: 'Mexilhões, amêijoas, ostras, lulas, polvo',
      nl: 'Mosselen, kokkels, oesters, inktvis, octopus',
      pl: 'Małże, przegrzebki, ostrygi, kalmary, ośmiornice',
      ru: 'Мидии, моллюски, устрицы, кальмары, осьминог',
      sv: 'Musslor, venusmusslor, ostron, bläckfisk',
      zh: '贻贝、蛤蜊、牡蛎、鱿鱼、章鱼',
      ja: 'ムール貝、アサリ、カキ、イカ、タコ',
      ko: '홍합, 조개, 굴, 오징어, 문어',
      th: 'หอยแมลงภู่ หอยลาย หอยนางรม ปลาหมึก หมึกยักษ์',
      ar: 'بلح البحر، محار، أويستر، حبار، أخطبوط',
    },
  },
  fava_beans: {
    examples: ['🫛', '🥘', '🥗', '🍲'],
    description: {
      it: 'Fave, zuppa di fave, purè di fave, favata, minestre',
      en: 'Fava beans, fava bean soup, fava bean purée, stews',
      fr: 'Fèves, soupe de fèves, purée de fèves, ragoûts',
      de: 'Saubohnen, Bohnensuppe, Bohnenpüree, Eintöpfe',
      es: 'Habas, sopa de habas, puré de habas, guisos',
      pt: 'Favas, sopa de favas, puré de favas, ensopados',
      nl: 'Tuinbonen, bonensoep, bonenpuree, stoofpotten',
      pl: 'Bób, zupa z bobu, puree z bobu, gulasz',
      ru: 'Бобы, суп из бобов, пюре из бобов, рагу',
      sv: 'Bondbönor, bönsoppa, bönpuré, grytor',
      zh: '蚕豆、蚕豆汤、蚕豆泥、炖菜',
      ja: 'ソラマメ、ソラマメスープ、ソラマメピューレ、シチュー',
      ko: '잠두콩, 잠두콩 수프, 잠두콩 퓌레, 스튜',
      th: 'ถั่วปากอ้า ซุปถั่วปากอ้า ถั่วปากอ้าบด สตูว์',
      ar: 'فول، شوربة فول، فول مدمس، يخنات',
    },
    warning: {
      it: '⚠️ Deficit di G6PD: anche piccole quantità possono causare crisi emolitica',
      en: '⚠️ G6PD deficiency: even small amounts can cause hemolytic crisis',
      fr: '⚠️ Déficit en G6PD : même de petites quantités peuvent provoquer une crise hémolytique',
      de: '⚠️ G6PD-Mangel: Selbst kleine Mengen können eine hämolytische Krise auslösen',
      es: '⚠️ Deficiencia de G6PD: incluso pequeñas cantidades pueden causar crisis hemolítica',
      pt: '⚠️ Deficiência de G6PD: mesmo pequenas quantidades podem causar crise hemolítica',
      nl: '⚠️ G6PD-tekort: zelfs kleine hoeveelheden kunnen een hemolytische crisis veroorzaken',
      pl: '⚠️ Niedobór G6PD: nawet małe ilości mogą wywołać przełom hemolityczny',
      ru: '⚠️ Дефицит Г6ФД: даже малые количества могут вызвать гемолитический криз',
      sv: '⚠️ G6PD-brist: även små mängder kan orsaka hemolytisk kris',
      zh: '⚠️ G6PD缺乏症：即使少量也可能引起溶血性危象',
      ja: '⚠️ G6PD欠損症：少量でも溶血性クリーゼを引き起こす可能性があります',
      ko: '⚠️ G6PD 결핍증: 소량으로도 용혈성 위기를 유발할 수 있습니다',
      th: '⚠️ ภาวะพร่องเอนไซม์ G6PD: แม้ปริมาณเล็กน้อยก็อาจทำให้เกิดภาวะเม็ดเลือดแดงแตก',
      ar: '⚠️ نقص إنزيم G6PD: حتى الكميات الصغيرة قد تسبب أزمة انحلالية',
    },
  },
};
