import { Allergen } from '../types';

export const ALLERGENS: Allergen[] = [
  {
    id: 'gluten',
    icon: '🌾',
    translations: {
      it: 'Glutine (cereali)',
      en: 'Gluten (cereals)',
      fr: 'Gluten (céréales)',
      de: 'Gluten (Getreide)',
      es: 'Gluten (cereales)',
      pt: 'Glúten (cereais)',
      nl: 'Gluten (granen)',
      pl: 'Gluten (zboża)',
      ru: 'Глютен (злаки)',
      sv: 'Gluten (spannmål)',
      zh: '麸质（谷物）',
      ja: 'グルテン（穀物）',
      ko: '글루텐 (곡물)',
      th: 'กลูเตน (ธัญพืช)',
      ar: 'الغلوتين (الحبوب)',
    },
  },
  {
    id: 'crustaceans',
    icon: '🦐',
    translations: {
      it: 'Crostacei',
      en: 'Crustaceans',
      fr: 'Crustacés',
      de: 'Krebstiere',
      es: 'Crustáceos',
      pt: 'Crustáceos',
      nl: 'Schaaldieren',
      pl: 'Skorupiaki',
      ru: 'Ракообразные',
      sv: 'Kräftdjur',
      zh: '甲壳类动物',
      ja: '甲殻類',
      ko: '갑각류',
      th: 'สัตว์จำพวกกุ้ง',
      ar: 'القشريات',
    },
  },
  {
    id: 'eggs',
    icon: '🥚',
    translations: {
      it: 'Uova',
      en: 'Eggs',
      fr: 'Œufs',
      de: 'Eier',
      es: 'Huevos',
      pt: 'Ovos',
      nl: 'Eieren',
      pl: 'Jaja',
      ru: 'Яйца',
      sv: 'Ägg',
      zh: '鸡蛋',
      ja: '卵',
      ko: '달걀',
      th: 'ไข่',
      ar: 'البيض',
    },
  },
  {
    id: 'fish',
    icon: '🐟',
    translations: {
      it: 'Pesce',
      en: 'Fish',
      fr: 'Poisson',
      de: 'Fisch',
      es: 'Pescado',
      pt: 'Peixe',
      nl: 'Vis',
      pl: 'Ryby',
      ru: 'Рыба',
      sv: 'Fisk',
      zh: '鱼类',
      ja: '魚',
      ko: '생선',
      th: 'ปลา',
      ar: 'السمك',
    },
  },
  {
    id: 'peanuts',
    icon: '🥜',
    translations: {
      it: 'Arachidi',
      en: 'Peanuts',
      fr: 'Arachides',
      de: 'Erdnüsse',
      es: 'Cacahuetes',
      pt: 'Amendoins',
      nl: 'Pinda\'s',
      pl: 'Orzeszki ziemne',
      ru: 'Арахис',
      sv: 'Jordnötter',
      zh: '花生',
      ja: 'ピーナッツ',
      ko: '땅콩',
      th: 'ถั่วลิสง',
      ar: 'الفول السوداني',
    },
  },
  {
    id: 'soy',
    icon: '🫘',
    translations: {
      it: 'Soia',
      en: 'Soy',
      fr: 'Soja',
      de: 'Soja',
      es: 'Soja',
      pt: 'Soja',
      nl: 'Soja',
      pl: 'Soja',
      ru: 'Соя',
      sv: 'Soja',
      zh: '大豆',
      ja: '大豆',
      ko: '대두',
      th: 'ถั่วเหลือง',
      ar: 'الصويا',
    },
  },
  {
    id: 'milk',
    icon: '🥛',
    translations: {
      it: 'Latte e latticini',
      en: 'Milk and dairy',
      fr: 'Lait et produits laitiers',
      de: 'Milch und Milchprodukte',
      es: 'Leche y lácteos',
      pt: 'Leite e laticínios',
      nl: 'Melk en zuivel',
      pl: 'Mleko i nabiał',
      ru: 'Молоко и молочные продукты',
      sv: 'Mjölk och mejeriprodukter',
      zh: '牛奶和乳制品',
      ja: '乳製品',
      ko: '우유 및 유제품',
      th: 'นมและผลิตภัณฑ์นม',
      ar: 'الحليب ومنتجات الألبان',
    },
  },
  {
    id: 'nuts',
    icon: '🌰',
    translations: {
      it: 'Frutta a guscio',
      en: 'Tree nuts',
      fr: 'Fruits à coque',
      de: 'Schalenfrüchte',
      es: 'Frutos secos',
      pt: 'Frutos de casca rija',
      nl: 'Noten',
      pl: 'Orzechy',
      ru: 'Орехи',
      sv: 'Nötter',
      zh: '坚果',
      ja: 'ナッツ類',
      ko: '견과류',
      th: 'ถั่วเปลือกแข็ง',
      ar: 'المكسرات',
    },
  },
  {
    id: 'celery',
    icon: '🥬',
    translations: {
      it: 'Sedano',
      en: 'Celery',
      fr: 'Céleri',
      de: 'Sellerie',
      es: 'Apio',
      pt: 'Aipo',
      nl: 'Selderij',
      pl: 'Seler',
      ru: 'Сельдерей',
      sv: 'Selleri',
      zh: '芹菜',
      ja: 'セロリ',
      ko: '셀러리',
      th: 'ขึ้นฉ่าย',
      ar: 'الكرفس',
    },
  },
  {
    id: 'mustard',
    icon: '🟡',
    translations: {
      it: 'Senape',
      en: 'Mustard',
      fr: 'Moutarde',
      de: 'Senf',
      es: 'Mostaza',
      pt: 'Mostarda',
      nl: 'Mosterd',
      pl: 'Gorczyca',
      ru: 'Горчица',
      sv: 'Senap',
      zh: '芥末',
      ja: 'マスタード',
      ko: '겨자',
      th: 'มัสตาร์ด',
      ar: 'الخردل',
    },
  },
  {
    id: 'sesame',
    icon: '🫓',
    translations: {
      it: 'Semi di sesamo',
      en: 'Sesame seeds',
      fr: 'Graines de sésame',
      de: 'Sesamsamen',
      es: 'Semillas de sésamo',
      pt: 'Sementes de sésamo',
      nl: 'Sesamzaad',
      pl: 'Nasiona sezamu',
      ru: 'Семена кунжута',
      sv: 'Sesamfrön',
      zh: '芝麻',
      ja: 'ゴマ',
      ko: '참깨',
      th: 'งา',
      ar: 'بذور السمسم',
    },
  },
  {
    id: 'sulfites',
    icon: '🍷',
    translations: {
      it: 'Anidride solforosa e solfiti',
      en: 'Sulfur dioxide and sulfites',
      fr: 'Dioxyde de soufre et sulfites',
      de: 'Schwefeldioxid und Sulfite',
      es: 'Dióxido de azufre y sulfitos',
      pt: 'Dióxido de enxofre e sulfitos',
      nl: 'Zwaveldioxide en sulfieten',
      pl: 'Dwutlenek siarki i siarczyny',
      ru: 'Диоксид серы и сульфиты',
      sv: 'Svaveldioxid och sulfiter',
      zh: '二氧化硫和亚硫酸盐',
      ja: '亜硫酸塩',
      ko: '아황산염',
      th: 'ซัลเฟอร์ไดออกไซด์และซัลไฟต์',
      ar: 'ثاني أكسيد الكبريت والكبريتيت',
    },
  },
  {
    id: 'lupin',
    icon: '🌸',
    translations: {
      it: 'Lupini',
      en: 'Lupin',
      fr: 'Lupin',
      de: 'Lupinen',
      es: 'Altramuces',
      pt: 'Tremoços',
      nl: 'Lupine',
      pl: 'Łubin',
      ru: 'Люпин',
      sv: 'Lupin',
      zh: '羽扇豆',
      ja: 'ルピナス',
      ko: '루핀',
      th: 'ลูปิน',
      ar: 'الترمس',
    },
  },
  {
    id: 'mollusks',
    icon: '🦪',
    translations: {
      it: 'Molluschi',
      en: 'Mollusks',
      fr: 'Mollusques',
      de: 'Weichtiere',
      es: 'Moluscos',
      pt: 'Moluscos',
      nl: 'Weekdieren',
      pl: 'Mięczaki',
      ru: 'Моллюски',
      sv: 'Blötdjur',
      zh: '软体动物',
      ja: '軟体動物',
      ko: '연체동물',
      th: 'หอย',
      ar: 'الرخويات',
    },
  },
];

export const getAllergenById = (id: string): Allergen | undefined => {
  return ALLERGENS.find((a) => a.id === id);
};
