// Mappa code ISO 3166-1 alpha-2 → nome paese nelle 5 lingue UI.
// Generata una tantum dai dati CLDR di Node (Intl.DisplayNames).
// Hermes su React Native non implementa Intl.DisplayNames, quindi serve una
// tabella statica a runtime. Per rigenerare/aggiornare: usare uno snippet Node
// con `new Intl.DisplayNames([lang], { type: 'region' })` su tutti i codici AA-ZZ.

import type { AppLanguage } from '../types';

export const COUNTRY_NAMES: Record<AppLanguage, Record<string, string>> = {
  it: {
    AC: "Isola Ascensione",
    AD: "Andorra",
    AE: "Emirati Arabi Uniti",
    AF: "Afghanistan",
    AG: "Antigua e Barbuda",
    AI: "Anguilla",
    AL: "Albania",
    AM: "Armenia",
    AN: "Curaçao",
    AO: "Angola",
    AQ: "Antartide",
    AR: "Argentina",
    AS: "Samoa Americane",
    AT: "Austria",
    AU: "Australia",
    AW: "Aruba",
    AX: "Isole Åland",
    AZ: "Azerbaigian",
    BA: "Bosnia ed Erzegovina",
    BB: "Barbados",
    BD: "Bangladesh",
    BE: "Belgio",
    BF: "Burkina Faso",
    BG: "Bulgaria",
    BH: "Bahrein",
    BI: "Burundi",
    BJ: "Benin",
    BL: "Saint-Barthélemy",
    BM: "Bermuda",
    BN: "Brunei",
    BO: "Bolivia",
    BQ: "Caraibi Olandesi",
    BR: "Brasile",
    BS: "Bahamas",
    BT: "Bhutan",
    BU: "Myanmar (Birmania)",
    BV: "Isola Bouvet",
    BW: "Botswana",
    BY: "Bielorussia",
    BZ: "Belize",
    CA: "Canada",
    CC: "Isole Cocos (Keeling)",
    CD: "Congo - Kinshasa",
    CF: "Repubblica Centrafricana",
    CG: "Congo-Brazzaville",
    CH: "Svizzera",
    CI: "Costa d’Avorio",
    CK: "Isole Cook",
    CL: "Cile",
    CM: "Camerun",
    CN: "Cina",
    CO: "Colombia",
    CP: "Isola di Clipperton",
    CR: "Costa Rica",
    CS: "Serbia",
    CU: "Cuba",
    CV: "Capo Verde",
    CW: "Curaçao",
    CX: "Isola Christmas",
    CY: "Cipro",
    CZ: "Cechia",
    DD: "Germania",
    DE: "Germania",
    DG: "Diego Garcia",
    DJ: "Gibuti",
    DK: "Danimarca",
    DM: "Dominica",
    DO: "Repubblica Dominicana",
    DY: "Benin",
    DZ: "Algeria",
    EA: "Ceuta e Melilla",
    EC: "Ecuador",
    EE: "Estonia",
    EG: "Egitto",
    EH: "Sahara Occidentale",
    ER: "Eritrea",
    ES: "Spagna",
    ET: "Etiopia",
    EU: "Unione europea",
    EZ: "Eurozona",
    FI: "Finlandia",
    FJ: "Figi",
    FK: "Isole Falkland",
    FM: "Micronesia",
    FO: "Isole Fær Øer",
    FR: "Francia",
    FX: "Francia",
    GA: "Gabon",
    GB: "Regno Unito",
    GD: "Grenada",
    GE: "Georgia",
    GF: "Guyana Francese",
    GG: "Guernsey",
    GH: "Ghana",
    GI: "Gibilterra",
    GL: "Groenlandia",
    GM: "Gambia",
    GN: "Guinea",
    GP: "Guadalupa",
    GQ: "Guinea Equatoriale",
    GR: "Grecia",
    GS: "Georgia del Sud e Sandwich Australi",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HK: "RAS di Hong Kong",
    HM: "Isole Heard e McDonald",
    HN: "Honduras",
    HR: "Croazia",
    HT: "Haiti",
    HU: "Ungheria",
    HV: "Burkina Faso",
    IC: "Isole Canarie",
    ID: "Indonesia",
    IE: "Irlanda",
    IL: "Israele",
    IM: "Isola di Man",
    IN: "India",
    IO: "Territorio Britannico dell’Oceano Indiano",
    IQ: "Iraq",
    IR: "Iran",
    IS: "Islanda",
    IT: "Italia",
    JE: "Jersey",
    JM: "Giamaica",
    JO: "Giordania",
    JP: "Giappone",
    KE: "Kenya",
    KG: "Kirghizistan",
    KH: "Cambogia",
    KI: "Kiribati",
    KM: "Comore",
    KN: "Saint Kitts e Nevis",
    KP: "Corea del Nord",
    KR: "Corea del Sud",
    KW: "Kuwait",
    KY: "Isole Cayman",
    KZ: "Kazakistan",
    LA: "Laos",
    LB: "Libano",
    LC: "Saint Lucia",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Liberia",
    LS: "Lesotho",
    LT: "Lituania",
    LU: "Lussemburgo",
    LV: "Lettonia",
    LY: "Libia",
    MA: "Marocco",
    MC: "Monaco",
    MD: "Moldavia",
    ME: "Montenegro",
    MF: "Saint Martin",
    MG: "Madagascar",
    MH: "Isole Marshall",
    MK: "Macedonia del Nord",
    ML: "Mali",
    MM: "Myanmar (Birmania)",
    MN: "Mongolia",
    MO: "RAS di Macao",
    MP: "Isole Marianne Settentrionali",
    MQ: "Martinica",
    MR: "Mauritania",
    MS: "Montserrat",
    MT: "Malta",
    MU: "Mauritius",
    MV: "Maldive",
    MW: "Malawi",
    MX: "Messico",
    MY: "Malaysia",
    MZ: "Mozambico",
    NA: "Namibia",
    NC: "Nuova Caledonia",
    NE: "Niger",
    NF: "Isola Norfolk",
    NG: "Nigeria",
    NH: "Vanuatu",
    NI: "Nicaragua",
    NL: "Paesi Bassi",
    NO: "Norvegia",
    NP: "Nepal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "Nuova Zelanda",
    OM: "Oman",
    PA: "Panama",
    PE: "Perù",
    PF: "Polinesia Francese",
    PG: "Papua Nuova Guinea",
    PH: "Filippine",
    PK: "Pakistan",
    PL: "Polonia",
    PM: "Saint-Pierre e Miquelon",
    PN: "Isole Pitcairn",
    PR: "Portorico",
    PS: "Territori Palestinesi",
    PT: "Portogallo",
    PW: "Palau",
    PY: "Paraguay",
    QA: "Qatar",
    QO: "Oceania lontana",
    RE: "Riunione",
    RH: "Zimbabwe",
    RO: "Romania",
    RS: "Serbia",
    RU: "Russia",
    RW: "Ruanda",
    SA: "Arabia Saudita",
    SB: "Isole Salomone",
    SC: "Seychelles",
    SD: "Sudan",
    SE: "Svezia",
    SG: "Singapore",
    SH: "Sant’Elena",
    SI: "Slovenia",
    SJ: "Svalbard e Jan Mayen",
    SK: "Slovacchia",
    SL: "Sierra Leone",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somalia",
    SR: "Suriname",
    SS: "Sud Sudan",
    ST: "São Tomé e Príncipe",
    SU: "Russia",
    SV: "El Salvador",
    SX: "Sint Maarten",
    SY: "Siria",
    SZ: "Eswatini",
    TA: "Tristan da Cunha",
    TC: "Isole Turks e Caicos",
    TD: "Ciad",
    TF: "Terre Australi Francesi",
    TG: "Togo",
    TH: "Thailandia",
    TJ: "Tagikistan",
    TK: "Tokelau",
    TL: "Timor Est",
    TM: "Turkmenistan",
    TN: "Tunisia",
    TO: "Tonga",
    TP: "Timor Est",
    TR: "Turchia",
    TT: "Trinidad e Tobago",
    TV: "Tuvalu",
    TW: "Taiwan",
    TZ: "Tanzania",
    UA: "Ucraina",
    UG: "Uganda",
    UK: "Regno Unito",
    UM: "Isole Minori Esterne degli Stati Uniti",
    UN: "Nazioni Unite",
    US: "Stati Uniti",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VA: "Città del Vaticano",
    VC: "Saint Vincent e Grenadine",
    VD: "Vietnam",
    VE: "Venezuela",
    VG: "Isole Vergini Britanniche",
    VI: "Isole Vergini Americane",
    VN: "Vietnam",
    VU: "Vanuatu",
    WF: "Wallis e Futuna",
    WS: "Samoa",
    XA: "Pseudo-accenti",
    XB: "Pseudo-bidi",
    XK: "Kosovo",
    YD: "Yemen",
    YE: "Yemen",
    YT: "Mayotte",
    YU: "Serbia",
    ZA: "Sudafrica",
    ZM: "Zambia",
    ZR: "Congo - Kinshasa",
    ZW: "Zimbabwe",
    ZZ: "Regione sconosciuta",
  },
  en: {
    AC: "Ascension Island",
    AD: "Andorra",
    AE: "United Arab Emirates",
    AF: "Afghanistan",
    AG: "Antigua & Barbuda",
    AI: "Anguilla",
    AL: "Albania",
    AM: "Armenia",
    AN: "Curaçao",
    AO: "Angola",
    AQ: "Antarctica",
    AR: "Argentina",
    AS: "American Samoa",
    AT: "Austria",
    AU: "Australia",
    AW: "Aruba",
    AX: "Åland Islands",
    AZ: "Azerbaijan",
    BA: "Bosnia & Herzegovina",
    BB: "Barbados",
    BD: "Bangladesh",
    BE: "Belgium",
    BF: "Burkina Faso",
    BG: "Bulgaria",
    BH: "Bahrain",
    BI: "Burundi",
    BJ: "Benin",
    BL: "St. Barthélemy",
    BM: "Bermuda",
    BN: "Brunei",
    BO: "Bolivia",
    BQ: "Caribbean Netherlands",
    BR: "Brazil",
    BS: "Bahamas",
    BT: "Bhutan",
    BU: "Myanmar (Burma)",
    BV: "Bouvet Island",
    BW: "Botswana",
    BY: "Belarus",
    BZ: "Belize",
    CA: "Canada",
    CC: "Cocos (Keeling) Islands",
    CD: "Congo - Kinshasa",
    CF: "Central African Republic",
    CG: "Congo - Brazzaville",
    CH: "Switzerland",
    CI: "Côte d’Ivoire",
    CK: "Cook Islands",
    CL: "Chile",
    CM: "Cameroon",
    CN: "China",
    CO: "Colombia",
    CP: "Clipperton Island",
    CQ: "Sark",
    CR: "Costa Rica",
    CS: "Serbia",
    CU: "Cuba",
    CV: "Cape Verde",
    CW: "Curaçao",
    CX: "Christmas Island",
    CY: "Cyprus",
    CZ: "Czechia",
    DD: "Germany",
    DE: "Germany",
    DG: "Diego Garcia",
    DJ: "Djibouti",
    DK: "Denmark",
    DM: "Dominica",
    DO: "Dominican Republic",
    DY: "Benin",
    DZ: "Algeria",
    EA: "Ceuta & Melilla",
    EC: "Ecuador",
    EE: "Estonia",
    EG: "Egypt",
    EH: "Western Sahara",
    ER: "Eritrea",
    ES: "Spain",
    ET: "Ethiopia",
    EU: "European Union",
    EZ: "Eurozone",
    FI: "Finland",
    FJ: "Fiji",
    FK: "Falkland Islands",
    FM: "Micronesia",
    FO: "Faroe Islands",
    FR: "France",
    FX: "France",
    GA: "Gabon",
    GB: "United Kingdom",
    GD: "Grenada",
    GE: "Georgia",
    GF: "French Guiana",
    GG: "Guernsey",
    GH: "Ghana",
    GI: "Gibraltar",
    GL: "Greenland",
    GM: "Gambia",
    GN: "Guinea",
    GP: "Guadeloupe",
    GQ: "Equatorial Guinea",
    GR: "Greece",
    GS: "South Georgia & South Sandwich Islands",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HK: "Hong Kong SAR China",
    HM: "Heard & McDonald Islands",
    HN: "Honduras",
    HR: "Croatia",
    HT: "Haiti",
    HU: "Hungary",
    HV: "Burkina Faso",
    IC: "Canary Islands",
    ID: "Indonesia",
    IE: "Ireland",
    IL: "Israel",
    IM: "Isle of Man",
    IN: "India",
    IO: "British Indian Ocean Territory",
    IQ: "Iraq",
    IR: "Iran",
    IS: "Iceland",
    IT: "Italy",
    JE: "Jersey",
    JM: "Jamaica",
    JO: "Jordan",
    JP: "Japan",
    KE: "Kenya",
    KG: "Kyrgyzstan",
    KH: "Cambodia",
    KI: "Kiribati",
    KM: "Comoros",
    KN: "St. Kitts & Nevis",
    KP: "North Korea",
    KR: "South Korea",
    KW: "Kuwait",
    KY: "Cayman Islands",
    KZ: "Kazakhstan",
    LA: "Laos",
    LB: "Lebanon",
    LC: "St. Lucia",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Liberia",
    LS: "Lesotho",
    LT: "Lithuania",
    LU: "Luxembourg",
    LV: "Latvia",
    LY: "Libya",
    MA: "Morocco",
    MC: "Monaco",
    MD: "Moldova",
    ME: "Montenegro",
    MF: "St. Martin",
    MG: "Madagascar",
    MH: "Marshall Islands",
    MK: "North Macedonia",
    ML: "Mali",
    MM: "Myanmar (Burma)",
    MN: "Mongolia",
    MO: "Macao SAR China",
    MP: "Northern Mariana Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MS: "Montserrat",
    MT: "Malta",
    MU: "Mauritius",
    MV: "Maldives",
    MW: "Malawi",
    MX: "Mexico",
    MY: "Malaysia",
    MZ: "Mozambique",
    NA: "Namibia",
    NC: "New Caledonia",
    NE: "Niger",
    NF: "Norfolk Island",
    NG: "Nigeria",
    NH: "Vanuatu",
    NI: "Nicaragua",
    NL: "Netherlands",
    NO: "Norway",
    NP: "Nepal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "New Zealand",
    OM: "Oman",
    PA: "Panama",
    PE: "Peru",
    PF: "French Polynesia",
    PG: "Papua New Guinea",
    PH: "Philippines",
    PK: "Pakistan",
    PL: "Poland",
    PM: "St. Pierre & Miquelon",
    PN: "Pitcairn Islands",
    PR: "Puerto Rico",
    PS: "Palestinian Territories",
    PT: "Portugal",
    PW: "Palau",
    PY: "Paraguay",
    QA: "Qatar",
    QO: "Outlying Oceania",
    RE: "Réunion",
    RH: "Zimbabwe",
    RO: "Romania",
    RS: "Serbia",
    RU: "Russia",
    RW: "Rwanda",
    SA: "Saudi Arabia",
    SB: "Solomon Islands",
    SC: "Seychelles",
    SD: "Sudan",
    SE: "Sweden",
    SG: "Singapore",
    SH: "St. Helena",
    SI: "Slovenia",
    SJ: "Svalbard & Jan Mayen",
    SK: "Slovakia",
    SL: "Sierra Leone",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somalia",
    SR: "Suriname",
    SS: "South Sudan",
    ST: "São Tomé & Príncipe",
    SU: "Russia",
    SV: "El Salvador",
    SX: "Sint Maarten",
    SY: "Syria",
    SZ: "Eswatini",
    TA: "Tristan da Cunha",
    TC: "Turks & Caicos Islands",
    TD: "Chad",
    TF: "French Southern Territories",
    TG: "Togo",
    TH: "Thailand",
    TJ: "Tajikistan",
    TK: "Tokelau",
    TL: "Timor-Leste",
    TM: "Turkmenistan",
    TN: "Tunisia",
    TO: "Tonga",
    TP: "Timor-Leste",
    TR: "Türkiye",
    TT: "Trinidad & Tobago",
    TV: "Tuvalu",
    TW: "Taiwan",
    TZ: "Tanzania",
    UA: "Ukraine",
    UG: "Uganda",
    UK: "United Kingdom",
    UM: "U.S. Outlying Islands",
    UN: "United Nations",
    US: "United States",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VA: "Vatican City",
    VC: "St. Vincent & Grenadines",
    VD: "Vietnam",
    VE: "Venezuela",
    VG: "British Virgin Islands",
    VI: "U.S. Virgin Islands",
    VN: "Vietnam",
    VU: "Vanuatu",
    WF: "Wallis & Futuna",
    WS: "Samoa",
    XA: "Pseudo-Accents",
    XB: "Pseudo-Bidi",
    XK: "Kosovo",
    YD: "Yemen",
    YE: "Yemen",
    YT: "Mayotte",
    YU: "Serbia",
    ZA: "South Africa",
    ZM: "Zambia",
    ZR: "Congo - Kinshasa",
    ZW: "Zimbabwe",
    ZZ: "Unknown Region",
  },
  es: {
    AC: "Isla de la Ascensión",
    AD: "Andorra",
    AE: "Emiratos Árabes Unidos",
    AF: "Afganistán",
    AG: "Antigua y Barbuda",
    AI: "Anguila",
    AL: "Albania",
    AM: "Armenia",
    AN: "Curazao",
    AO: "Angola",
    AQ: "Antártida",
    AR: "Argentina",
    AS: "Samoa Americana",
    AT: "Austria",
    AU: "Australia",
    AW: "Aruba",
    AX: "Islas Aland",
    AZ: "Azerbaiyán",
    BA: "Bosnia y Herzegovina",
    BB: "Barbados",
    BD: "Bangladés",
    BE: "Bélgica",
    BF: "Burkina Faso",
    BG: "Bulgaria",
    BH: "Baréin",
    BI: "Burundi",
    BJ: "Benín",
    BL: "San Bartolomé",
    BM: "Bermudas",
    BN: "Brunéi",
    BO: "Bolivia",
    BQ: "Caribe neerlandés",
    BR: "Brasil",
    BS: "Bahamas",
    BT: "Bután",
    BU: "Myanmar (Birmania)",
    BV: "Isla Bouvet",
    BW: "Botsuana",
    BY: "Bielorrusia",
    BZ: "Belice",
    CA: "Canadá",
    CC: "Islas Cocos",
    CD: "República Democrática del Congo",
    CF: "República Centroafricana",
    CG: "Congo",
    CH: "Suiza",
    CI: "Côte d’Ivoire",
    CK: "Islas Cook",
    CL: "Chile",
    CM: "Camerún",
    CN: "China",
    CO: "Colombia",
    CP: "Isla Clipperton",
    CR: "Costa Rica",
    CS: "Serbia",
    CU: "Cuba",
    CV: "Cabo Verde",
    CW: "Curazao",
    CX: "Isla de Navidad",
    CY: "Chipre",
    CZ: "Chequia",
    DD: "Alemania",
    DE: "Alemania",
    DG: "Diego García",
    DJ: "Yibuti",
    DK: "Dinamarca",
    DM: "Dominica",
    DO: "República Dominicana",
    DY: "Benín",
    DZ: "Argelia",
    EA: "Ceuta y Melilla",
    EC: "Ecuador",
    EE: "Estonia",
    EG: "Egipto",
    EH: "Sáhara Occidental",
    ER: "Eritrea",
    ES: "España",
    ET: "Etiopía",
    EU: "Unión Europea",
    EZ: "zona del euro",
    FI: "Finlandia",
    FJ: "Fiyi",
    FK: "Islas Malvinas",
    FM: "Micronesia",
    FO: "Islas Feroe",
    FR: "Francia",
    FX: "Francia",
    GA: "Gabón",
    GB: "Reino Unido",
    GD: "Granada",
    GE: "Georgia",
    GF: "Guayana Francesa",
    GG: "Guernesey",
    GH: "Ghana",
    GI: "Gibraltar",
    GL: "Groenlandia",
    GM: "Gambia",
    GN: "Guinea",
    GP: "Guadalupe",
    GQ: "Guinea Ecuatorial",
    GR: "Grecia",
    GS: "Islas Georgia del Sur y Sandwich del Sur",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guinea-Bisáu",
    GY: "Guyana",
    HK: "RAE de Hong Kong (China)",
    HM: "Islas Heard y McDonald",
    HN: "Honduras",
    HR: "Croacia",
    HT: "Haití",
    HU: "Hungría",
    HV: "Burkina Faso",
    IC: "Canarias",
    ID: "Indonesia",
    IE: "Irlanda",
    IL: "Israel",
    IM: "Isla de Man",
    IN: "India",
    IO: "Territorio Británico del Océano Índico",
    IQ: "Irak",
    IR: "Irán",
    IS: "Islandia",
    IT: "Italia",
    JE: "Jersey",
    JM: "Jamaica",
    JO: "Jordania",
    JP: "Japón",
    KE: "Kenia",
    KG: "Kirguistán",
    KH: "Camboya",
    KI: "Kiribati",
    KM: "Comoras",
    KN: "San Cristóbal y Nieves",
    KP: "Corea del Norte",
    KR: "Corea del Sur",
    KW: "Kuwait",
    KY: "Islas Caimán",
    KZ: "Kazajistán",
    LA: "Laos",
    LB: "Líbano",
    LC: "Santa Lucía",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Liberia",
    LS: "Lesoto",
    LT: "Lituania",
    LU: "Luxemburgo",
    LV: "Letonia",
    LY: "Libia",
    MA: "Marruecos",
    MC: "Mónaco",
    MD: "Moldavia",
    ME: "Montenegro",
    MF: "San Martín",
    MG: "Madagascar",
    MH: "Islas Marshall",
    MK: "Macedonia del Norte",
    ML: "Mali",
    MM: "Myanmar (Birmania)",
    MN: "Mongolia",
    MO: "RAE de Macao (China)",
    MP: "Islas Marianas del Norte",
    MQ: "Martinica",
    MR: "Mauritania",
    MS: "Montserrat",
    MT: "Malta",
    MU: "Mauricio",
    MV: "Maldivas",
    MW: "Malaui",
    MX: "México",
    MY: "Malasia",
    MZ: "Mozambique",
    NA: "Namibia",
    NC: "Nueva Caledonia",
    NE: "Níger",
    NF: "Isla Norfolk",
    NG: "Nigeria",
    NH: "Vanuatu",
    NI: "Nicaragua",
    NL: "Países Bajos",
    NO: "Noruega",
    NP: "Nepal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "Nueva Zelanda",
    OM: "Omán",
    PA: "Panamá",
    PE: "Perú",
    PF: "Polinesia Francesa",
    PG: "Papúa Nueva Guinea",
    PH: "Filipinas",
    PK: "Pakistán",
    PL: "Polonia",
    PM: "San Pedro y Miquelón",
    PN: "Islas Pitcairn",
    PR: "Puerto Rico",
    PS: "Territorios Palestinos",
    PT: "Portugal",
    PW: "Palaos",
    PY: "Paraguay",
    QA: "Catar",
    QO: "Territorios alejados de Oceanía",
    RE: "Reunión",
    RH: "Zimbabue",
    RO: "Rumanía",
    RS: "Serbia",
    RU: "Rusia",
    RW: "Ruanda",
    SA: "Arabia Saudí",
    SB: "Islas Salomón",
    SC: "Seychelles",
    SD: "Sudán",
    SE: "Suecia",
    SG: "Singapur",
    SH: "Santa Elena",
    SI: "Eslovenia",
    SJ: "Svalbard y Jan Mayen",
    SK: "Eslovaquia",
    SL: "Sierra Leona",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somalia",
    SR: "Surinam",
    SS: "Sudán del Sur",
    ST: "Santo Tomé y Príncipe",
    SU: "Rusia",
    SV: "El Salvador",
    SX: "Sint Maarten",
    SY: "Siria",
    SZ: "Esuatini",
    TA: "Tristán de Acuña",
    TC: "Islas Turcas y Caicos",
    TD: "Chad",
    TF: "Territorios Australes Franceses",
    TG: "Togo",
    TH: "Tailandia",
    TJ: "Tayikistán",
    TK: "Tokelau",
    TL: "Timor-Leste",
    TM: "Turkmenistán",
    TN: "Túnez",
    TO: "Tonga",
    TP: "Timor-Leste",
    TR: "Turquía",
    TT: "Trinidad y Tobago",
    TV: "Tuvalu",
    TW: "Taiwán",
    TZ: "Tanzania",
    UA: "Ucrania",
    UG: "Uganda",
    UK: "Reino Unido",
    UM: "Islas menores alejadas de EE. UU.",
    UN: "Naciones Unidas",
    US: "Estados Unidos",
    UY: "Uruguay",
    UZ: "Uzbekistán",
    VA: "Ciudad del Vaticano",
    VC: "San Vicente y las Granadinas",
    VD: "Vietnam",
    VE: "Venezuela",
    VG: "Islas Vírgenes Británicas",
    VI: "Islas Vírgenes de EE. UU.",
    VN: "Vietnam",
    VU: "Vanuatu",
    WF: "Wallis y Futuna",
    WS: "Samoa",
    XA: "Pseudoacentos",
    XB: "Pseudobidi",
    XK: "Kosovo",
    YD: "Yemen",
    YE: "Yemen",
    YT: "Mayotte",
    YU: "Serbia",
    ZA: "Sudáfrica",
    ZM: "Zambia",
    ZR: "República Democrática del Congo",
    ZW: "Zimbabue",
    ZZ: "Región desconocida",
  },
  de: {
    AC: "Ascension",
    AD: "Andorra",
    AE: "Vereinigte Arabische Emirate",
    AF: "Afghanistan",
    AG: "Antigua und Barbuda",
    AI: "Anguilla",
    AL: "Albanien",
    AM: "Armenien",
    AN: "Curaçao",
    AO: "Angola",
    AQ: "Antarktis",
    AR: "Argentinien",
    AS: "Amerikanisch-Samoa",
    AT: "Österreich",
    AU: "Australien",
    AW: "Aruba",
    AX: "Ålandinseln",
    AZ: "Aserbaidschan",
    BA: "Bosnien und Herzegowina",
    BB: "Barbados",
    BD: "Bangladesch",
    BE: "Belgien",
    BF: "Burkina Faso",
    BG: "Bulgarien",
    BH: "Bahrain",
    BI: "Burundi",
    BJ: "Benin",
    BL: "St. Barthélemy",
    BM: "Bermuda",
    BN: "Brunei Darussalam",
    BO: "Bolivien",
    BQ: "Karibische Niederlande",
    BR: "Brasilien",
    BS: "Bahamas",
    BT: "Bhutan",
    BU: "Myanmar",
    BV: "Bouvetinsel",
    BW: "Botsuana",
    BY: "Belarus",
    BZ: "Belize",
    CA: "Kanada",
    CC: "Kokosinseln",
    CD: "Kongo-Kinshasa",
    CF: "Zentralafrikanische Republik",
    CG: "Kongo-Brazzaville",
    CH: "Schweiz",
    CI: "Côte d’Ivoire",
    CK: "Cookinseln",
    CL: "Chile",
    CM: "Kamerun",
    CN: "China",
    CO: "Kolumbien",
    CP: "Clipperton-Insel",
    CR: "Costa Rica",
    CS: "Serbien",
    CU: "Kuba",
    CV: "Cabo Verde",
    CW: "Curaçao",
    CX: "Weihnachtsinsel",
    CY: "Zypern",
    CZ: "Tschechien",
    DD: "Deutschland",
    DE: "Deutschland",
    DG: "Diego Garcia",
    DJ: "Dschibuti",
    DK: "Dänemark",
    DM: "Dominica",
    DO: "Dominikanische Republik",
    DY: "Benin",
    DZ: "Algerien",
    EA: "Ceuta und Melilla",
    EC: "Ecuador",
    EE: "Estland",
    EG: "Ägypten",
    EH: "Westsahara",
    ER: "Eritrea",
    ES: "Spanien",
    ET: "Äthiopien",
    EU: "Europäische Union",
    EZ: "Eurozone",
    FI: "Finnland",
    FJ: "Fidschi",
    FK: "Falklandinseln",
    FM: "Mikronesien",
    FO: "Färöer",
    FR: "Frankreich",
    FX: "Frankreich",
    GA: "Gabun",
    GB: "Vereinigtes Königreich",
    GD: "Grenada",
    GE: "Georgien",
    GF: "Französisch-Guayana",
    GG: "Guernsey",
    GH: "Ghana",
    GI: "Gibraltar",
    GL: "Grönland",
    GM: "Gambia",
    GN: "Guinea",
    GP: "Guadeloupe",
    GQ: "Äquatorialguinea",
    GR: "Griechenland",
    GS: "Südgeorgien und die Südlichen Sandwichinseln",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HK: "Sonderverwaltungsregion Hongkong",
    HM: "Heard und McDonaldinseln",
    HN: "Honduras",
    HR: "Kroatien",
    HT: "Haiti",
    HU: "Ungarn",
    HV: "Burkina Faso",
    IC: "Kanarische Inseln",
    ID: "Indonesien",
    IE: "Irland",
    IL: "Israel",
    IM: "Isle of Man",
    IN: "Indien",
    IO: "Britisches Territorium im Indischen Ozean",
    IQ: "Irak",
    IR: "Iran",
    IS: "Island",
    IT: "Italien",
    JE: "Jersey",
    JM: "Jamaika",
    JO: "Jordanien",
    JP: "Japan",
    KE: "Kenia",
    KG: "Kirgisistan",
    KH: "Kambodscha",
    KI: "Kiribati",
    KM: "Komoren",
    KN: "St. Kitts und Nevis",
    KP: "Nordkorea",
    KR: "Südkorea",
    KW: "Kuwait",
    KY: "Kaimaninseln",
    KZ: "Kasachstan",
    LA: "Laos",
    LB: "Libanon",
    LC: "St. Lucia",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Liberia",
    LS: "Lesotho",
    LT: "Litauen",
    LU: "Luxemburg",
    LV: "Lettland",
    LY: "Libyen",
    MA: "Marokko",
    MC: "Monaco",
    MD: "Republik Moldau",
    ME: "Montenegro",
    MF: "St. Martin",
    MG: "Madagaskar",
    MH: "Marshallinseln",
    MK: "Nordmazedonien",
    ML: "Mali",
    MM: "Myanmar",
    MN: "Mongolei",
    MO: "Sonderverwaltungsregion Macau",
    MP: "Nördliche Marianen",
    MQ: "Martinique",
    MR: "Mauretanien",
    MS: "Montserrat",
    MT: "Malta",
    MU: "Mauritius",
    MV: "Malediven",
    MW: "Malawi",
    MX: "Mexiko",
    MY: "Malaysia",
    MZ: "Mosambik",
    NA: "Namibia",
    NC: "Neukaledonien",
    NE: "Niger",
    NF: "Norfolkinsel",
    NG: "Nigeria",
    NH: "Vanuatu",
    NI: "Nicaragua",
    NL: "Niederlande",
    NO: "Norwegen",
    NP: "Nepal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "Neuseeland",
    OM: "Oman",
    PA: "Panama",
    PE: "Peru",
    PF: "Französisch-Polynesien",
    PG: "Papua-Neuguinea",
    PH: "Philippinen",
    PK: "Pakistan",
    PL: "Polen",
    PM: "St. Pierre und Miquelon",
    PN: "Pitcairninseln",
    PR: "Puerto Rico",
    PS: "Palästinensische Autonomiegebiete",
    PT: "Portugal",
    PW: "Palau",
    PY: "Paraguay",
    QA: "Katar",
    QO: "Äußeres Ozeanien",
    RE: "Réunion",
    RH: "Simbabwe",
    RO: "Rumänien",
    RS: "Serbien",
    RU: "Russland",
    RW: "Ruanda",
    SA: "Saudi-Arabien",
    SB: "Salomonen",
    SC: "Seychellen",
    SD: "Sudan",
    SE: "Schweden",
    SG: "Singapur",
    SH: "St. Helena",
    SI: "Slowenien",
    SJ: "Spitzbergen und Jan Mayen",
    SK: "Slowakei",
    SL: "Sierra Leone",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somalia",
    SR: "Suriname",
    SS: "Südsudan",
    ST: "São Tomé und Príncipe",
    SU: "Russland",
    SV: "El Salvador",
    SX: "Sint Maarten",
    SY: "Syrien",
    SZ: "Eswatini",
    TA: "Tristan da Cunha",
    TC: "Turks- und Caicosinseln",
    TD: "Tschad",
    TF: "Französische Süd- und Antarktisgebiete",
    TG: "Togo",
    TH: "Thailand",
    TJ: "Tadschikistan",
    TK: "Tokelau",
    TL: "Timor-Leste",
    TM: "Turkmenistan",
    TN: "Tunesien",
    TO: "Tonga",
    TP: "Timor-Leste",
    TR: "Türkei",
    TT: "Trinidad und Tobago",
    TV: "Tuvalu",
    TW: "Taiwan",
    TZ: "Tansania",
    UA: "Ukraine",
    UG: "Uganda",
    UK: "Vereinigtes Königreich",
    UM: "Amerikanische Überseeinseln",
    UN: "Vereinte Nationen",
    US: "Vereinigte Staaten",
    UY: "Uruguay",
    UZ: "Usbekistan",
    VA: "Vatikanstadt",
    VC: "St. Vincent und die Grenadinen",
    VD: "Vietnam",
    VE: "Venezuela",
    VG: "Britische Jungferninseln",
    VI: "Amerikanische Jungferninseln",
    VN: "Vietnam",
    VU: "Vanuatu",
    WF: "Wallis und Futuna",
    WS: "Samoa",
    XA: "Pseudo-Akzente",
    XB: "Pseudo-Bidi",
    XK: "Kosovo",
    YD: "Jemen",
    YE: "Jemen",
    YT: "Mayotte",
    YU: "Serbien",
    ZA: "Südafrika",
    ZM: "Sambia",
    ZR: "Kongo-Kinshasa",
    ZW: "Simbabwe",
    ZZ: "Unbekannte Region",
  },
  fr: {
    AC: "Île de l’Ascension",
    AD: "Andorre",
    AE: "Émirats arabes unis",
    AF: "Afghanistan",
    AG: "Antigua-et-Barbuda",
    AI: "Anguilla",
    AL: "Albanie",
    AM: "Arménie",
    AN: "Curaçao",
    AO: "Angola",
    AQ: "Antarctique",
    AR: "Argentine",
    AS: "Samoa américaines",
    AT: "Autriche",
    AU: "Australie",
    AW: "Aruba",
    AX: "Îles Åland",
    AZ: "Azerbaïdjan",
    BA: "Bosnie-Herzégovine",
    BB: "Barbade",
    BD: "Bangladesh",
    BE: "Belgique",
    BF: "Burkina Faso",
    BG: "Bulgarie",
    BH: "Bahreïn",
    BI: "Burundi",
    BJ: "Bénin",
    BL: "Saint-Barthélemy",
    BM: "Bermudes",
    BN: "Brunei",
    BO: "Bolivie",
    BQ: "Pays-Bas caribéens",
    BR: "Brésil",
    BS: "Bahamas",
    BT: "Bhoutan",
    BU: "Myanmar (Birmanie)",
    BV: "Île Bouvet",
    BW: "Botswana",
    BY: "Biélorussie",
    BZ: "Belize",
    CA: "Canada",
    CC: "Îles Cocos",
    CD: "Congo-Kinshasa",
    CF: "République centrafricaine",
    CG: "Congo-Brazzaville",
    CH: "Suisse",
    CI: "Côte d’Ivoire",
    CK: "Îles Cook",
    CL: "Chili",
    CM: "Cameroun",
    CN: "Chine",
    CO: "Colombie",
    CP: "Île Clipperton",
    CR: "Costa Rica",
    CS: "Serbie",
    CU: "Cuba",
    CV: "Cap-Vert",
    CW: "Curaçao",
    CX: "Île Christmas",
    CY: "Chypre",
    CZ: "Tchéquie",
    DD: "Allemagne",
    DE: "Allemagne",
    DG: "Diego Garcia",
    DJ: "Djibouti",
    DK: "Danemark",
    DM: "Dominique",
    DO: "République dominicaine",
    DY: "Bénin",
    DZ: "Algérie",
    EA: "Ceuta et Melilla",
    EC: "Équateur",
    EE: "Estonie",
    EG: "Égypte",
    EH: "Sahara occidental",
    ER: "Érythrée",
    ES: "Espagne",
    ET: "Éthiopie",
    EU: "Union européenne",
    EZ: "zone euro",
    FI: "Finlande",
    FJ: "Fidji",
    FK: "Îles Malouines",
    FM: "Micronésie",
    FO: "Îles Féroé",
    FR: "France",
    FX: "France",
    GA: "Gabon",
    GB: "Royaume-Uni",
    GD: "Grenade",
    GE: "Géorgie",
    GF: "Guyane française",
    GG: "Guernesey",
    GH: "Ghana",
    GI: "Gibraltar",
    GL: "Groenland",
    GM: "Gambie",
    GN: "Guinée",
    GP: "Guadeloupe",
    GQ: "Guinée équatoriale",
    GR: "Grèce",
    GS: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guinée-Bissau",
    GY: "Guyana",
    HK: "R.A.S. chinoise de Hong Kong",
    HM: "Îles Heard-et-MacDonald",
    HN: "Honduras",
    HR: "Croatie",
    HT: "Haïti",
    HU: "Hongrie",
    HV: "Burkina Faso",
    IC: "Îles Canaries",
    ID: "Indonésie",
    IE: "Irlande",
    IL: "Israël",
    IM: "Île de Man",
    IN: "Inde",
    IO: "Territoire britannique de l’océan Indien",
    IQ: "Irak",
    IR: "Iran",
    IS: "Islande",
    IT: "Italie",
    JE: "Jersey",
    JM: "Jamaïque",
    JO: "Jordanie",
    JP: "Japon",
    KE: "Kenya",
    KG: "Kirghizstan",
    KH: "Cambodge",
    KI: "Kiribati",
    KM: "Comores",
    KN: "Saint-Christophe-et-Niévès",
    KP: "Corée du Nord",
    KR: "Corée du Sud",
    KW: "Koweït",
    KY: "Îles Caïmans",
    KZ: "Kazakhstan",
    LA: "Laos",
    LB: "Liban",
    LC: "Sainte-Lucie",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Liberia",
    LS: "Lesotho",
    LT: "Lituanie",
    LU: "Luxembourg",
    LV: "Lettonie",
    LY: "Libye",
    MA: "Maroc",
    MC: "Monaco",
    MD: "Moldavie",
    ME: "Monténégro",
    MF: "Saint-Martin",
    MG: "Madagascar",
    MH: "Îles Marshall",
    MK: "Macédoine du Nord",
    ML: "Mali",
    MM: "Myanmar (Birmanie)",
    MN: "Mongolie",
    MO: "R.A.S. chinoise de Macao",
    MP: "Îles Mariannes du Nord",
    MQ: "Martinique",
    MR: "Mauritanie",
    MS: "Montserrat",
    MT: "Malte",
    MU: "Maurice",
    MV: "Maldives",
    MW: "Malawi",
    MX: "Mexique",
    MY: "Malaisie",
    MZ: "Mozambique",
    NA: "Namibie",
    NC: "Nouvelle-Calédonie",
    NE: "Niger",
    NF: "Île Norfolk",
    NG: "Nigeria",
    NH: "Vanuatu",
    NI: "Nicaragua",
    NL: "Pays-Bas",
    NO: "Norvège",
    NP: "Népal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "Nouvelle-Zélande",
    OM: "Oman",
    PA: "Panama",
    PE: "Pérou",
    PF: "Polynésie française",
    PG: "Papouasie-Nouvelle-Guinée",
    PH: "Philippines",
    PK: "Pakistan",
    PL: "Pologne",
    PM: "Saint-Pierre-et-Miquelon",
    PN: "Îles Pitcairn",
    PR: "Porto Rico",
    PS: "Territoires palestiniens",
    PT: "Portugal",
    PW: "Palaos",
    PY: "Paraguay",
    QA: "Qatar",
    QO: "régions éloignées de l’Océanie",
    RE: "La Réunion",
    RH: "Zimbabwe",
    RO: "Roumanie",
    RS: "Serbie",
    RU: "Russie",
    RW: "Rwanda",
    SA: "Arabie saoudite",
    SB: "Îles Salomon",
    SC: "Seychelles",
    SD: "Soudan",
    SE: "Suède",
    SG: "Singapour",
    SH: "Sainte-Hélène",
    SI: "Slovénie",
    SJ: "Svalbard et Jan Mayen",
    SK: "Slovaquie",
    SL: "Sierra Leone",
    SM: "Saint-Marin",
    SN: "Sénégal",
    SO: "Somalie",
    SR: "Suriname",
    SS: "Soudan du Sud",
    ST: "Sao Tomé-et-Principe",
    SU: "Russie",
    SV: "Salvador",
    SX: "Saint-Martin (partie néerlandaise)",
    SY: "Syrie",
    SZ: "Eswatini",
    TA: "Tristan da Cunha",
    TC: "Îles Turques-et-Caïques",
    TD: "Tchad",
    TF: "Terres australes françaises",
    TG: "Togo",
    TH: "Thaïlande",
    TJ: "Tadjikistan",
    TK: "Tokelau",
    TL: "Timor oriental",
    TM: "Turkménistan",
    TN: "Tunisie",
    TO: "Tonga",
    TP: "Timor oriental",
    TR: "Turquie",
    TT: "Trinité-et-Tobago",
    TV: "Tuvalu",
    TW: "Taïwan",
    TZ: "Tanzanie",
    UA: "Ukraine",
    UG: "Ouganda",
    UK: "Royaume-Uni",
    UM: "Îles mineures éloignées des États-Unis",
    UN: "Nations Unies",
    US: "États-Unis",
    UY: "Uruguay",
    UZ: "Ouzbékistan",
    VA: "État de la Cité du Vatican",
    VC: "Saint-Vincent-et-les Grenadines",
    VD: "Viêt Nam",
    VE: "Venezuela",
    VG: "Îles Vierges britanniques",
    VI: "Îles Vierges des États-Unis",
    VN: "Viêt Nam",
    VU: "Vanuatu",
    WF: "Wallis-et-Futuna",
    WS: "Samoa",
    XA: "pseudo-accents",
    XB: "pseudo-bidi",
    XK: "Kosovo",
    YD: "Yémen",
    YE: "Yémen",
    YT: "Mayotte",
    YU: "Serbie",
    ZA: "Afrique du Sud",
    ZM: "Zambie",
    ZR: "Congo-Kinshasa",
    ZW: "Zimbabwe",
    ZZ: "région indéterminée",
  },
};
