// Diete e intolleranze per la sezione ristoranti.
// TODO merge: valutare se unificare con dietModes.ts della sezione card
import type { DietId, Language } from '../types';

export interface DietInfo {
  id: DietId;
  icon: string;
  translations: Record<Language, string>;
}

export const DIETS: readonly DietInfo[] = [
  {
    id: 'vegetarian',
    icon: '🥬',
    translations: {
      it: 'Vegetariano',
      en: 'Vegetarian',
      fr: 'Végétarien',
      de: 'Vegetarisch',
      es: 'Vegetariano',
      pt: 'Vegetariano',
      nl: 'Vegetarisch',
      pl: 'Wegetariański',
      ru: 'Вегетарианец',
      sv: 'Vegetarian',
      zh: '素食',
      ja: 'ベジタリアン',
      ko: '채식주의',
      th: 'มังสวิรัติ',
      ar: 'نباتي',
    },
  },
  {
    id: 'vegan',
    icon: '🌱',
    translations: {
      it: 'Vegano',
      en: 'Vegan',
      fr: 'Végétalien',
      de: 'Vegan',
      es: 'Vegano',
      pt: 'Vegano',
      nl: 'Veganistisch',
      pl: 'Wegański',
      ru: 'Веган',
      sv: 'Vegan',
      zh: '纯素',
      ja: 'ヴィーガン',
      ko: '비건',
      th: 'วีแกน',
      ar: 'نباتي صرف',
    },
  },
  {
    id: 'histamine',
    icon: '🧪',
    translations: {
      it: 'Istamina',
      en: 'Histamine',
      fr: 'Histamine',
      de: 'Histamin',
      es: 'Histamina',
      pt: 'Histamina',
      nl: 'Histamine',
      pl: 'Histamina',
      ru: 'Гистамин',
      sv: 'Histamin',
      zh: '组胺',
      ja: 'ヒスタミン',
      ko: '히스타민',
      th: 'ฮิสตามีน',
      ar: 'الهيستامين',
    },
  },
  {
    id: 'nickel',
    icon: '🪙',
    translations: {
      it: 'Nichel',
      en: 'Nickel',
      fr: 'Nickel',
      de: 'Nickel',
      es: 'Níquel',
      pt: 'Níquel',
      nl: 'Nikkel',
      pl: 'Nikiel',
      ru: 'Никель',
      sv: 'Nickel',
      zh: '镍',
      ja: 'ニッケル',
      ko: '니켈',
      th: 'นิกเกิล',
      ar: 'النيكل',
    },
  },
  {
    id: 'diabetes',
    icon: '🩸',
    translations: {
      it: 'Diabete',
      en: 'Diabetes',
      fr: 'Diabète',
      de: 'Diabetes',
      es: 'Diabetes',
      pt: 'Diabetes',
      nl: 'Diabetes',
      pl: 'Cukrzyca',
      ru: 'Диабет',
      sv: 'Diabetes',
      zh: '糖尿病',
      ja: '糖尿病',
      ko: '당뇨병',
      th: 'เบาหวาน',
      ar: 'السكري',
    },
  },
];
