/**
 * Mappatura codice lingua → nomi dei paesi dove si parla quella lingua.
 * Include varianti in tutte le 5 lingue app (it, en, es, de, fr) per la ricerca.
 */
export const LANGUAGE_COUNTRIES: Record<string, string[]> = {
  // ── Built-in ──
  it: ['Italy', 'Italia', 'Italien', 'Italie', 'San Marino', 'Svizzera', 'Switzerland', 'Schweiz', 'Suisse', 'Suiza'],
  en: ['UK', 'USA', 'England', 'United Kingdom', 'United States', 'Australia', 'Canada', 'New Zealand', 'Ireland', 'Regno Unito', 'Stati Uniti', 'Inghilterra', 'Vereinigtes Königreich', 'Vereinigte Staaten', 'Royaume-Uni', 'États-Unis', 'Estados Unidos', 'Reino Unido', 'Irlanda', 'Jamaica', 'Giamaica', 'Jamaika', 'Jamaïque', 'Bahamas', 'Barbados', 'Trinidad', 'Tobago', 'Belize', 'Guyana', 'South Africa', 'Sudafrica', 'Südafrika', 'Afrique du Sud', 'Sudáfrica', 'Ghana', 'Kenya', 'Kenia', 'Nigeria', 'Uganda', 'Namibia', 'Botswana', 'Zimbabwe', 'Simbabwe', 'Zambia', 'Sambia', 'Zambie', 'Rwanda', 'Ruanda', 'Gambia', 'Seychelles', 'India', 'Pakistan', 'Philippines', 'Filippine', 'Philippinen', 'Filipinas', 'Hong Kong', 'Malaysia', 'Malesia', 'Malta', 'Malte', 'Cyprus', 'Cipro', 'Zypern', 'Chypre', 'Chipre', 'Singapore', 'Singapur', 'Singapour', 'Gibraltar', 'Bermuda', 'Fiji', 'Figi', 'Fidschi', 'Fidji', 'Mauritius'],
  fr: ['France', 'Francia', 'Frankreich', 'Belgium', 'Belgio', 'Belgien', 'Belgique', 'Bélgica', 'Svizzera', 'Switzerland', 'Schweiz', 'Suisse', 'Suiza', 'Luxembourg', 'Lussemburgo', 'Luxemburg', 'Monaco', 'Canada', 'Kanada', 'Senegal', 'Cameroon', 'Camerun', 'Kamerun', 'Cameroun', 'Camerún', 'Ivory Coast', 'Costa d\'Avorio', 'Elfenbeinküste', 'Côte d\'Ivoire', 'Costa de Marfil', 'Morocco', 'Marocco', 'Marokko', 'Maroc', 'Marruecos', 'Algeria', 'Algerien', 'Algérie', 'Argelia', 'Tunisia', 'Tunisie', 'Tunesien', 'Túnez', 'Madagascar', 'Madagaskar', 'Seychelles', 'Mauritius', 'Maurice', 'Rwanda', 'Ruanda', 'Tahiti', 'French Polynesia', 'Polinesia Francese', 'Polynésie française', 'Réunion', 'Martinique', 'Martinica', 'Guadeloupe', 'Guadalupa', 'New Caledonia', 'Nuova Caledonia', 'Neukaledonien', 'Nouvelle-Calédonie', 'Haiti', 'Haïti', 'Congo', 'Mali', 'Niger', 'Togo', 'Benin'],
  de: ['Germany', 'Germania', 'Deutschland', 'Allemagne', 'Alemania', 'Austria', 'Österreich', 'Autriche', 'Svizzera', 'Switzerland', 'Schweiz', 'Suisse', 'Suiza', 'Liechtenstein'],
  es: ['Spain', 'Spagna', 'Spanien', 'Espagne', 'España', 'Mexico', 'Messico', 'Mexiko', 'Mexique', 'México', 'Argentina', 'Colombia', 'Peru', 'Perù', 'Chile', 'Cuba', 'Venezuela', 'Ecuador', 'Bolivia', 'Bolivien', 'Bolivie', 'Paraguay', 'Uruguay', 'Panama', 'Panamá', 'Costa Rica', 'Guatemala', 'Honduras', 'El Salvador', 'Nicaragua', 'Dominican Republic', 'Repubblica Dominicana', 'Dominikanische Republik', 'République dominicaine', 'República Dominicana', 'Puerto Rico', 'Equatorial Guinea', 'Guinea Equatoriale', 'Äquatorialguinea', 'Guinée équatoriale', 'Guinea Ecuatorial'],
  pt: ['Portugal', 'Portogallo', 'Brazil', 'Brasile', 'Brasilien', 'Brésil', 'Brasil', 'Mozambique', 'Mosambik', 'Mozambico', 'Angola', 'Cape Verde', 'Capo Verde', 'Kap Verde', 'Cap-Vert', 'Cabo Verde', 'Macau', 'Macao', 'East Timor', 'Timor Est', 'Osttimor', 'Timor oriental', 'Timor Oriental', 'Guinea-Bissau', 'São Tomé'],
  nl: ['Netherlands', 'Olanda', 'Holland', 'Niederlande', 'Pays-Bas', 'Países Bajos', 'Belgium', 'Belgio', 'Belgien', 'Belgique', 'Bélgica', 'Suriname', 'Aruba', 'Curaçao', 'Curacao'],
  pl: ['Poland', 'Polonia', 'Polen', 'Pologne'],
  ru: ['Russia', 'Rusia', 'Russland', 'Russie', 'Belarus', 'Bielorussia', 'Weißrussland', 'Biélorussie', 'Bielorrusia'],
  sv: ['Sweden', 'Svezia', 'Schweden', 'Suède', 'Suecia'],
  zh: ['China', 'Cina', 'Taiwan', 'Singapore', 'Singapur', 'Singapour', 'Hong Kong'],
  ja: ['Japan', 'Giappone', 'Japón', 'Japon'],
  ko: ['South Korea', 'Korea', 'Corea', 'Südkorea', 'Corée', 'Corea del Sur'],
  th: ['Thailand', 'Thailandia', 'Tailandia', 'Thaïlande'],
  ar: ['Saudi Arabia', 'Arabia Saudita', 'Egypt', 'Egitto', 'Ägypten', 'Égypte', 'Egipto', 'UAE', 'Emirati', 'Morocco', 'Marocco', 'Marokko', 'Maroc', 'Marruecos', 'Tunisia', 'Tunisie', 'Tunesien', 'Túnez', 'Jordan', 'Giordania', 'Jordanien', 'Jordanie', 'Jordania', 'Lebanon', 'Libano', 'Libanon', 'Liban', 'Líbano', 'Qatar', 'Oman', 'Kuwait', 'Bahrain', 'Algeria', 'Algerien', 'Algérie', 'Argelia', 'Libya', 'Libia', 'Libyen', 'Libye', 'Iraq', 'Irak', 'Syria', 'Siria', 'Syrien', 'Syrie', 'Yemen', 'Jemen', 'Yémen', 'Palestine', 'Palestina', 'Palästina', 'Sudan', 'Soudan', 'Mauritania', 'Mauritanien', 'Mauritanie'],

  // ── Europa ──
  el: ['Greece', 'Grecia', 'Griechenland', 'Grèce', 'Cyprus', 'Cipro', 'Zypern', 'Chypre', 'Chipre'],
  tr: ['Turkey', 'Turchia', 'Türkei', 'Turquie', 'Turquía', 'Cyprus', 'Cipro', 'Zypern', 'Chypre', 'Chipre'],
  cs: ['Czech Republic', 'Czechia', 'Repubblica Ceca', 'Tschechien', 'République tchèque', 'República Checa', 'Cechia'],
  hu: ['Hungary', 'Ungheria', 'Ungarn', 'Hongrie', 'Hungría'],
  ro: ['Romania', 'Rumänien', 'Roumanie', 'Rumania', 'Moldova', 'Moldavia', 'Moldavie', 'Moldawien'],
  uk: ['Ukraine', 'Ucraina', 'Ukraina'],
  da: ['Denmark', 'Danimarca', 'Dänemark', 'Danemark', 'Dinamarca'],
  fi: ['Finland', 'Finlandia', 'Finnland', 'Finlande'],
  no: ['Norway', 'Norvegia', 'Norwegen', 'Norvège', 'Noruega'],
  hr: ['Croatia', 'Croazia', 'Kroatien', 'Croatie', 'Croacia'],
  bg: ['Bulgaria', 'Bulgarien', 'Bulgarie'],
  sk: ['Slovakia', 'Slovacchia', 'Slowakei', 'Slovaquie', 'Eslovaquia'],
  sl: ['Slovenia', 'Slowenien', 'Slovénie', 'Eslovenia'],
  sr: ['Serbia', 'Serbien', 'Serbie'],
  lt: ['Lithuania', 'Lituania', 'Litauen', 'Lituanie'],
  lv: ['Latvia', 'Lettonia', 'Lettland', 'Lettonie', 'Letonia'],
  et: ['Estonia', 'Estland', 'Estonie'],
  is: ['Iceland', 'Islanda', 'Island', 'Islande', 'Islandia'],
  mk: ['North Macedonia', 'Macedonia', 'Mazedonien', 'Macédoine', 'Nordmazedonien'],
  sq: ['Albania', 'Albanien', 'Albanie', 'Kosovo'],
  bs: ['Bosnia', 'Bosnia-Erzegovina', 'Bosnien', 'Bosnie', 'Bosnia-Herzegovina'],
  mt: ['Malta', 'Malte'],
  ga: ['Ireland', 'Irlanda', 'Irland', 'Irlande'],
  cy: ['Wales', 'Galles', 'Gales', 'Pays de Galles'],
  ca: ['Catalonia', 'Catalogna', 'Katalonien', 'Catalogne', 'Cataluña', 'Andorra'],
  eu: ['Basque Country', 'Paesi Baschi', 'Baskenland', 'Pays basque', 'País Vasco'],
  gl: ['Galicia', 'Galizia', 'Galicien', 'Galice'],

  // ── Asia ──
  he: ['Israel', 'Israele'],
  hi: ['India', 'Indien', 'Inde'],
  pa: ['India', 'Punjab'],
  gu: ['India', 'Gujarat'],
  kn: ['India', 'Karnataka'],
  ml: ['India', 'Kerala'],
  vi: ['Vietnam', 'Viet Nam'],
  id: ['Indonesia', 'Indonesien', 'Indonésie'],
  ms: ['Malaysia', 'Malesia', 'Malaysien', 'Malaisie', 'Malasia', 'Brunei'],
  tl: ['Philippines', 'Filippine', 'Philippinen', 'Filipinas'],
  bn: ['Bangladesh', 'India', 'Bengal', 'Bengala'],
  ta: ['India', 'Sri Lanka', 'Tamil Nadu', 'Singapore', 'Singapur', 'Singapour'],
  te: ['India', 'Telangana', 'Andhra Pradesh'],
  mr: ['India', 'Maharashtra'],
  ur: ['Pakistan'],
  fa: ['Iran', 'Persia', 'Persien', 'Perse', 'Afghanistan', 'Tajikistan'],
  ps: ['Afghanistan'],
  ku: ['Kurdistan', 'Iraq', 'Irak'],
  ne: ['Nepal'],
  si: ['Sri Lanka'],
  dv: ['Maldives', 'Maldive', 'Malediven', 'Maldivas'],
  km: ['Cambodia', 'Cambogia', 'Kambodscha', 'Cambodge', 'Camboya'],
  lo: ['Laos'],
  my: ['Myanmar', 'Burma', 'Birmania', 'Birmanie'],
  ka: ['Georgia', 'Georgien', 'Géorgie', 'Giorgia'],
  hy: ['Armenia', 'Armenien', 'Arménie'],
  az: ['Azerbaijan', 'Azerbaigian', 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaiyán'],
  kk: ['Kazakhstan', 'Kazakistan', 'Kasachstan'],
  uz: ['Uzbekistan', 'Usbekistan', 'Ouzbékistan'],
  tg: ['Tajikistan', 'Tagikistan', 'Tadschikistan', 'Tadjikistan', 'Tayikistán'],
  ky: ['Kyrgyzstan', 'Kirghizistan', 'Kirgisistan', 'Kirghizstan'],
  tk: ['Turkmenistan', 'Turkménistan'],
  mn: ['Mongolia', 'Mongolie', 'Mongolei'],
  dz: ['Bhutan', 'Butan', 'Bhoutan', 'Bután'],

  // ── Africa ──
  sw: ['Kenya', 'Kenia', 'Tanzania', 'Tansania', 'Tanzanie', 'Tansanien', 'Uganda', 'Zanzibar', 'Sansibar'],
  af: ['South Africa', 'Sudafrica', 'Südafrika', 'Afrique du Sud', 'Sudáfrica', 'Namibia'],
  am: ['Ethiopia', 'Etiopia', 'Äthiopien', 'Éthiopie', 'Etiopía'],
  ha: ['Nigeria', 'Niger'],
  yo: ['Nigeria'],
  zu: ['South Africa', 'Sudafrica', 'Südafrika', 'Afrique du Sud', 'Sudáfrica'],
  so: ['Somalia', 'Somalie'],
  mg: ['Madagascar', 'Madagaskar'],

  // ── Altro ──
  ht: ['Haiti', 'Haïti'],
};
