import { AppLanguage } from '../types';

// Nomi delle lingue tradotti nelle lingue dell'app
// Usato per visualizzare e cercare le lingue nel picker
export const LANGUAGE_NAMES: Record<string, Record<AppLanguage, string>> = {
  // Lingue integrate
  it: { it: 'Italiano', en: 'Italian', es: 'Italiano', de: 'Italienisch', fr: 'Italien' },
  en: { it: 'Inglese', en: 'English', es: 'Inglés', de: 'Englisch', fr: 'Anglais' },
  fr: { it: 'Francese', en: 'French', es: 'Francés', de: 'Französisch', fr: 'Français' },
  de: { it: 'Tedesco', en: 'German', es: 'Alemán', de: 'Deutsch', fr: 'Allemand' },
  es: { it: 'Spagnolo', en: 'Spanish', es: 'Español', de: 'Spanisch', fr: 'Espagnol' },
  pt: { it: 'Portoghese', en: 'Portuguese', es: 'Portugués', de: 'Portugiesisch', fr: 'Portugais' },
  nl: { it: 'Olandese', en: 'Dutch', es: 'Neerlandés', de: 'Niederländisch', fr: 'Néerlandais' },
  pl: { it: 'Polacco', en: 'Polish', es: 'Polaco', de: 'Polnisch', fr: 'Polonais' },
  ru: { it: 'Russo', en: 'Russian', es: 'Ruso', de: 'Russisch', fr: 'Russe' },
  sv: { it: 'Svedese', en: 'Swedish', es: 'Sueco', de: 'Schwedisch', fr: 'Suédois' },
  zh: { it: 'Cinese', en: 'Chinese', es: 'Chino', de: 'Chinesisch', fr: 'Chinois' },
  ja: { it: 'Giapponese', en: 'Japanese', es: 'Japonés', de: 'Japanisch', fr: 'Japonais' },
  ko: { it: 'Coreano', en: 'Korean', es: 'Coreano', de: 'Koreanisch', fr: 'Coréen' },
  th: { it: 'Tailandese', en: 'Thai', es: 'Tailandés', de: 'Thailändisch', fr: 'Thaïlandais' },
  ar: { it: 'Arabo', en: 'Arabic', es: 'Árabe', de: 'Arabisch', fr: 'Arabe' },
  // Europa
  el: { it: 'Greco', en: 'Greek', es: 'Griego', de: 'Griechisch', fr: 'Grec' },
  tr: { it: 'Turco', en: 'Turkish', es: 'Turco', de: 'Türkisch', fr: 'Turc' },
  cs: { it: 'Ceco', en: 'Czech', es: 'Checo', de: 'Tschechisch', fr: 'Tchèque' },
  hu: { it: 'Ungherese', en: 'Hungarian', es: 'Húngaro', de: 'Ungarisch', fr: 'Hongrois' },
  ro: { it: 'Rumeno', en: 'Romanian', es: 'Rumano', de: 'Rumänisch', fr: 'Roumain' },
  uk: { it: 'Ucraino', en: 'Ukrainian', es: 'Ucraniano', de: 'Ukrainisch', fr: 'Ukrainien' },
  da: { it: 'Danese', en: 'Danish', es: 'Danés', de: 'Dänisch', fr: 'Danois' },
  fi: { it: 'Finlandese', en: 'Finnish', es: 'Finlandés', de: 'Finnisch', fr: 'Finnois' },
  no: { it: 'Norvegese', en: 'Norwegian', es: 'Noruego', de: 'Norwegisch', fr: 'Norvégien' },
  hr: { it: 'Croato', en: 'Croatian', es: 'Croata', de: 'Kroatisch', fr: 'Croate' },
  bg: { it: 'Bulgaro', en: 'Bulgarian', es: 'Búlgaro', de: 'Bulgarisch', fr: 'Bulgare' },
  sk: { it: 'Slovacco', en: 'Slovak', es: 'Eslovaco', de: 'Slowakisch', fr: 'Slovaque' },
  sl: { it: 'Sloveno', en: 'Slovenian', es: 'Esloveno', de: 'Slowenisch', fr: 'Slovène' },
  sr: { it: 'Serbo', en: 'Serbian', es: 'Serbio', de: 'Serbisch', fr: 'Serbe' },
  lt: { it: 'Lituano', en: 'Lithuanian', es: 'Lituano', de: 'Litauisch', fr: 'Lituanien' },
  lv: { it: 'Lettone', en: 'Latvian', es: 'Letón', de: 'Lettisch', fr: 'Letton' },
  et: { it: 'Estone', en: 'Estonian', es: 'Estonio', de: 'Estnisch', fr: 'Estonien' },
  is: { it: 'Islandese', en: 'Icelandic', es: 'Islandés', de: 'Isländisch', fr: 'Islandais' },
  mk: { it: 'Macedone', en: 'Macedonian', es: 'Macedonio', de: 'Mazedonisch', fr: 'Macédonien' },
  sq: { it: 'Albanese', en: 'Albanian', es: 'Albanés', de: 'Albanisch', fr: 'Albanais' },
  bs: { it: 'Bosniaco', en: 'Bosnian', es: 'Bosnio', de: 'Bosnisch', fr: 'Bosniaque' },
  mt: { it: 'Maltese', en: 'Maltese', es: 'Maltés', de: 'Maltesisch', fr: 'Maltais' },
  ga: { it: 'Irlandese', en: 'Irish', es: 'Irlandés', de: 'Irisch', fr: 'Irlandais' },
  cy: { it: 'Gallese', en: 'Welsh', es: 'Galés', de: 'Walisisch', fr: 'Gallois' },
  ca: { it: 'Catalano', en: 'Catalan', es: 'Catalán', de: 'Katalanisch', fr: 'Catalan' },
  eu: { it: 'Basco', en: 'Basque', es: 'Vasco', de: 'Baskisch', fr: 'Basque' },
  gl: { it: 'Galiziano', en: 'Galician', es: 'Gallego', de: 'Galicisch', fr: 'Galicien' },
  // Asia e Medio Oriente
  he: { it: 'Ebraico', en: 'Hebrew', es: 'Hebreo', de: 'Hebräisch', fr: 'Hébreu' },
  hi: { it: 'Hindi', en: 'Hindi', es: 'Hindi', de: 'Hindi', fr: 'Hindi' },
  vi: { it: 'Vietnamita', en: 'Vietnamese', es: 'Vietnamita', de: 'Vietnamesisch', fr: 'Vietnamien' },
  id: { it: 'Indonesiano', en: 'Indonesian', es: 'Indonesio', de: 'Indonesisch', fr: 'Indonésien' },
  ms: { it: 'Malese', en: 'Malay', es: 'Malayo', de: 'Malaiisch', fr: 'Malais' },
  tl: { it: 'Filippino', en: 'Filipino', es: 'Filipino', de: 'Filipino', fr: 'Filipino' },
  bn: { it: 'Bengalese', en: 'Bengali', es: 'Bengalí', de: 'Bengalisch', fr: 'Bengali' },
  ta: { it: 'Tamil', en: 'Tamil', es: 'Tamil', de: 'Tamil', fr: 'Tamoul' },
  te: { it: 'Telugu', en: 'Telugu', es: 'Telugu', de: 'Telugu', fr: 'Télougou' },
  mr: { it: 'Marathi', en: 'Marathi', es: 'Maratí', de: 'Marathi', fr: 'Marathi' },
  ur: { it: 'Urdu', en: 'Urdu', es: 'Urdu', de: 'Urdu', fr: 'Ourdou' },
  fa: { it: 'Persiano', en: 'Persian', es: 'Persa', de: 'Persisch', fr: 'Persan' },
  ne: { it: 'Nepalese', en: 'Nepali', es: 'Nepalí', de: 'Nepalesisch', fr: 'Népalais' },
  si: { it: 'Singalese', en: 'Sinhala', es: 'Cingalés', de: 'Singhalesisch', fr: 'Cingalais' },
  km: { it: 'Khmer', en: 'Khmer', es: 'Jemer', de: 'Khmer', fr: 'Khmer' },
  lo: { it: 'Laotiano', en: 'Lao', es: 'Laosiano', de: 'Laotisch', fr: 'Laotien' },
  my: { it: 'Birmano', en: 'Burmese', es: 'Birmano', de: 'Birmanisch', fr: 'Birman' },
  ka: { it: 'Georgiano', en: 'Georgian', es: 'Georgiano', de: 'Georgisch', fr: 'Géorgien' },
  hy: { it: 'Armeno', en: 'Armenian', es: 'Armenio', de: 'Armenisch', fr: 'Arménien' },
  az: { it: 'Azerbaigiano', en: 'Azerbaijani', es: 'Azerbaiyano', de: 'Aserbaidschanisch', fr: 'Azerbaïdjanais' },
  kk: { it: 'Kazako', en: 'Kazakh', es: 'Kazajo', de: 'Kasachisch', fr: 'Kazakh' },
  uz: { it: 'Uzbeco', en: 'Uzbek', es: 'Uzbeko', de: 'Usbekisch', fr: 'Ouzbek' },
  mn: { it: 'Mongolo', en: 'Mongolian', es: 'Mongol', de: 'Mongolisch', fr: 'Mongol' },
  // Africa
  sw: { it: 'Swahili', en: 'Swahili', es: 'Suajili', de: 'Swahili', fr: 'Swahili' },
  af: { it: 'Afrikaans', en: 'Afrikaans', es: 'Afrikáans', de: 'Afrikaans', fr: 'Afrikaans' },
  am: { it: 'Amarico', en: 'Amharic', es: 'Amárico', de: 'Amharisch', fr: 'Amharique' },
  ha: { it: 'Hausa', en: 'Hausa', es: 'Hausa', de: 'Hausa', fr: 'Haoussa' },
  yo: { it: 'Yoruba', en: 'Yoruba', es: 'Yoruba', de: 'Yoruba', fr: 'Yoruba' },
  zu: { it: 'Zulu', en: 'Zulu', es: 'Zulú', de: 'Zulu', fr: 'Zoulou' },
  // Altro
  eo: { it: 'Esperanto', en: 'Esperanto', es: 'Esperanto', de: 'Esperanto', fr: 'Espéranto' },
};

// Restituisce il nome localizzato di una lingua nella lingua corrente dell'app
export function getLocalizedLanguageName(langCode: string, appLang: AppLanguage): string | undefined {
  return LANGUAGE_NAMES[langCode]?.[appLang];
}
