import { AppLanguage } from '../types';

// Nomi delle lingue tradotti nelle lingue dell'app
// Usato per visualizzare e cercare le lingue nel picker
export const LANGUAGE_NAMES: Record<string, Record<AppLanguage, string>> = {
  // Lingue integrate
  it: { it: 'Italiano', en: 'Italian', es: 'Italiano', de: 'Italienisch', fr: 'Italien', pt: 'Italiano' },
  en: { it: 'Inglese', en: 'English', es: 'Inglés', de: 'Englisch', fr: 'Anglais', pt: 'Inglês' },
  fr: { it: 'Francese', en: 'French', es: 'Francés', de: 'Französisch', fr: 'Français', pt: 'Francês' },
  de: { it: 'Tedesco', en: 'German', es: 'Alemán', de: 'Deutsch', fr: 'Allemand', pt: 'Alemão' },
  es: { it: 'Spagnolo', en: 'Spanish', es: 'Español', de: 'Spanisch', fr: 'Espagnol', pt: 'Espanhol' },
  pt: { it: 'Portoghese', en: 'Portuguese', es: 'Portugués', de: 'Portugiesisch', fr: 'Portugais', pt: 'Português' },
  nl: { it: 'Olandese', en: 'Dutch', es: 'Neerlandés', de: 'Niederländisch', fr: 'Néerlandais', pt: 'Neerlandês' },
  pl: { it: 'Polacco', en: 'Polish', es: 'Polaco', de: 'Polnisch', fr: 'Polonais', pt: 'Polaco' },
  ru: { it: 'Russo', en: 'Russian', es: 'Ruso', de: 'Russisch', fr: 'Russe', pt: 'Russo' },
  sv: { it: 'Svedese', en: 'Swedish', es: 'Sueco', de: 'Schwedisch', fr: 'Suédois', pt: 'Sueco' },
  zh: { it: 'Cinese', en: 'Chinese', es: 'Chino', de: 'Chinesisch', fr: 'Chinois', pt: 'Chinês' },
  ja: { it: 'Giapponese', en: 'Japanese', es: 'Japonés', de: 'Japanisch', fr: 'Japonais', pt: 'Japonês' },
  ko: { it: 'Coreano', en: 'Korean', es: 'Coreano', de: 'Koreanisch', fr: 'Coréen', pt: 'Coreano' },
  th: { it: 'Tailandese', en: 'Thai', es: 'Tailandés', de: 'Thailändisch', fr: 'Thaïlandais', pt: 'Tailandês' },
  ar: { it: 'Arabo', en: 'Arabic', es: 'Árabe', de: 'Arabisch', fr: 'Arabe', pt: 'Árabe' },
  // Europa
  el: { it: 'Greco', en: 'Greek', es: 'Griego', de: 'Griechisch', fr: 'Grec', pt: 'Grego' },
  tr: { it: 'Turco', en: 'Turkish', es: 'Turco', de: 'Türkisch', fr: 'Turc', pt: 'Turco' },
  cs: { it: 'Ceco', en: 'Czech', es: 'Checo', de: 'Tschechisch', fr: 'Tchèque', pt: 'Checo' },
  hu: { it: 'Ungherese', en: 'Hungarian', es: 'Húngaro', de: 'Ungarisch', fr: 'Hongrois', pt: 'Húngaro' },
  ro: { it: 'Rumeno', en: 'Romanian', es: 'Rumano', de: 'Rumänisch', fr: 'Roumain', pt: 'Romeno' },
  uk: { it: 'Ucraino', en: 'Ukrainian', es: 'Ucraniano', de: 'Ukrainisch', fr: 'Ukrainien', pt: 'Ucraniano' },
  da: { it: 'Danese', en: 'Danish', es: 'Danés', de: 'Dänisch', fr: 'Danois', pt: 'Dinamarquês' },
  fi: { it: 'Finlandese', en: 'Finnish', es: 'Finlandés', de: 'Finnisch', fr: 'Finnois', pt: 'Finlandês' },
  no: { it: 'Norvegese', en: 'Norwegian', es: 'Noruego', de: 'Norwegisch', fr: 'Norvégien', pt: 'Norueguês' },
  hr: { it: 'Croato', en: 'Croatian', es: 'Croata', de: 'Kroatisch', fr: 'Croate', pt: 'Croata' },
  bg: { it: 'Bulgaro', en: 'Bulgarian', es: 'Búlgaro', de: 'Bulgarisch', fr: 'Bulgare', pt: 'Búlgaro' },
  sk: { it: 'Slovacco', en: 'Slovak', es: 'Eslovaco', de: 'Slowakisch', fr: 'Slovaque', pt: 'Eslovaco' },
  sl: { it: 'Sloveno', en: 'Slovenian', es: 'Esloveno', de: 'Slowenisch', fr: 'Slovène', pt: 'Esloveno' },
  sr: { it: 'Serbo', en: 'Serbian', es: 'Serbio', de: 'Serbisch', fr: 'Serbe', pt: 'Sérvio' },
  lt: { it: 'Lituano', en: 'Lithuanian', es: 'Lituano', de: 'Litauisch', fr: 'Lituanien', pt: 'Lituano' },
  lv: { it: 'Lettone', en: 'Latvian', es: 'Letón', de: 'Lettisch', fr: 'Letton', pt: 'Letão' },
  et: { it: 'Estone', en: 'Estonian', es: 'Estonio', de: 'Estnisch', fr: 'Estonien', pt: 'Estónio' },
  is: { it: 'Islandese', en: 'Icelandic', es: 'Islandés', de: 'Isländisch', fr: 'Islandais', pt: 'Islandês' },
  mk: { it: 'Macedone', en: 'Macedonian', es: 'Macedonio', de: 'Mazedonisch', fr: 'Macédonien', pt: 'Macedónio' },
  sq: { it: 'Albanese', en: 'Albanian', es: 'Albanés', de: 'Albanisch', fr: 'Albanais', pt: 'Albanês' },
  bs: { it: 'Bosniaco', en: 'Bosnian', es: 'Bosnio', de: 'Bosnisch', fr: 'Bosniaque', pt: 'Bósnio' },
  mt: { it: 'Maltese', en: 'Maltese', es: 'Maltés', de: 'Maltesisch', fr: 'Maltais', pt: 'Maltês' },
  ga: { it: 'Irlandese', en: 'Irish', es: 'Irlandés', de: 'Irisch', fr: 'Irlandais', pt: 'Irlandês' },
  cy: { it: 'Gallese', en: 'Welsh', es: 'Galés', de: 'Walisisch', fr: 'Gallois', pt: 'Galês' },
  ca: { it: 'Catalano', en: 'Catalan', es: 'Catalán', de: 'Katalanisch', fr: 'Catalan', pt: 'Catalão' },
  eu: { it: 'Basco', en: 'Basque', es: 'Vasco', de: 'Baskisch', fr: 'Basque', pt: 'Basco' },
  gl: { it: 'Galiziano', en: 'Galician', es: 'Gallego', de: 'Galicisch', fr: 'Galicien', pt: 'Galego' },
  // Asia e Medio Oriente
  he: { it: 'Ebraico', en: 'Hebrew', es: 'Hebreo', de: 'Hebräisch', fr: 'Hébreu', pt: 'Hebraico' },
  hi: { it: 'Hindi', en: 'Hindi', es: 'Hindi', de: 'Hindi', fr: 'Hindi', pt: 'Hindi' },
  pa: { it: 'Punjabi', en: 'Punjabi', es: 'Punyabí', de: 'Punjabi', fr: 'Pendjabi', pt: 'Panjabi' },
  gu: { it: 'Gujarati', en: 'Gujarati', es: 'Guyaratí', de: 'Gujarati', fr: 'Gujarati', pt: 'Guzerate' },
  kn: { it: 'Kannada', en: 'Kannada', es: 'Canarés', de: 'Kannada', fr: 'Kannada', pt: 'Canarim' },
  ml: { it: 'Malayalam', en: 'Malayalam', es: 'Malayalam', de: 'Malayalam', fr: 'Malayalam', pt: 'Malaiala' },
  vi: { it: 'Vietnamita', en: 'Vietnamese', es: 'Vietnamita', de: 'Vietnamesisch', fr: 'Vietnamien', pt: 'Vietnamita' },
  id: { it: 'Indonesiano', en: 'Indonesian', es: 'Indonesio', de: 'Indonesisch', fr: 'Indonésien', pt: 'Indonésio' },
  ms: { it: 'Malese', en: 'Malay', es: 'Malayo', de: 'Malaiisch', fr: 'Malais', pt: 'Malaio' },
  tl: { it: 'Filippino', en: 'Filipino', es: 'Filipino', de: 'Filipino', fr: 'Filipino', pt: 'Filipino' },
  bn: { it: 'Bengalese', en: 'Bengali', es: 'Bengalí', de: 'Bengalisch', fr: 'Bengali', pt: 'Bengalês' },
  ta: { it: 'Tamil', en: 'Tamil', es: 'Tamil', de: 'Tamil', fr: 'Tamoul', pt: 'Tâmil' },
  te: { it: 'Telugu', en: 'Telugu', es: 'Telugu', de: 'Telugu', fr: 'Télougou', pt: 'Telugu' },
  mr: { it: 'Marathi', en: 'Marathi', es: 'Maratí', de: 'Marathi', fr: 'Marathi', pt: 'Marata' },
  ur: { it: 'Urdu', en: 'Urdu', es: 'Urdu', de: 'Urdu', fr: 'Ourdou', pt: 'Urdu' },
  fa: { it: 'Persiano', en: 'Persian', es: 'Persa', de: 'Persisch', fr: 'Persan', pt: 'Persa' },
  ps: { it: 'Pashto', en: 'Pashto', es: 'Pastún', de: 'Paschtu', fr: 'Pachto', pt: 'Pastó' },
  ku: { it: 'Curdo', en: 'Kurdish', es: 'Kurdo', de: 'Kurdisch', fr: 'Kurde', pt: 'Curdo' },
  ne: { it: 'Nepalese', en: 'Nepali', es: 'Nepalí', de: 'Nepalesisch', fr: 'Népalais', pt: 'Nepalês' },
  si: { it: 'Singalese', en: 'Sinhala', es: 'Cingalés', de: 'Singhalesisch', fr: 'Cingalais', pt: 'Cingalês' },
  dv: { it: 'Dhivehi', en: 'Dhivehi', es: 'Divehi', de: 'Dhivehi', fr: 'Maldivien', pt: 'Divehi' },
  km: { it: 'Khmer', en: 'Khmer', es: 'Jemer', de: 'Khmer', fr: 'Khmer', pt: 'Khmer' },
  lo: { it: 'Laotiano', en: 'Lao', es: 'Laosiano', de: 'Laotisch', fr: 'Laotien', pt: 'Laosiano' },
  my: { it: 'Birmano', en: 'Burmese', es: 'Birmano', de: 'Birmanisch', fr: 'Birman', pt: 'Birmanês' },
  ka: { it: 'Georgiano', en: 'Georgian', es: 'Georgiano', de: 'Georgisch', fr: 'Géorgien', pt: 'Georgiano' },
  hy: { it: 'Armeno', en: 'Armenian', es: 'Armenio', de: 'Armenisch', fr: 'Arménien', pt: 'Arménio' },
  az: { it: 'Azerbaigiano', en: 'Azerbaijani', es: 'Azerbaiyano', de: 'Aserbaidschanisch', fr: 'Azerbaïdjanais', pt: 'Azerbaijano' },
  kk: { it: 'Kazako', en: 'Kazakh', es: 'Kazajo', de: 'Kasachisch', fr: 'Kazakh', pt: 'Cazaque' },
  uz: { it: 'Uzbeco', en: 'Uzbek', es: 'Uzbeko', de: 'Usbekisch', fr: 'Ouzbek', pt: 'Usbeque' },
  tg: { it: 'Tagico', en: 'Tajik', es: 'Tayiko', de: 'Tadschikisch', fr: 'Tadjik', pt: 'Tajique' },
  ky: { it: 'Kirghiso', en: 'Kyrgyz', es: 'Kirguís', de: 'Kirgisisch', fr: 'Kirghize', pt: 'Quirguiz' },
  tk: { it: 'Turkmeno', en: 'Turkmen', es: 'Turcomano', de: 'Turkmenisch', fr: 'Turkmène', pt: 'Turcomano' },
  mn: { it: 'Mongolo', en: 'Mongolian', es: 'Mongol', de: 'Mongolisch', fr: 'Mongol', pt: 'Mongol' },
  // Africa
  sw: { it: 'Swahili', en: 'Swahili', es: 'Suajili', de: 'Swahili', fr: 'Swahili', pt: 'Suaíli' },
  af: { it: 'Afrikaans', en: 'Afrikaans', es: 'Afrikáans', de: 'Afrikaans', fr: 'Afrikaans', pt: 'Africanês' },
  am: { it: 'Amarico', en: 'Amharic', es: 'Amárico', de: 'Amharisch', fr: 'Amharique', pt: 'Amárico' },
  ha: { it: 'Hausa', en: 'Hausa', es: 'Hausa', de: 'Hausa', fr: 'Haoussa', pt: 'Haúça' },
  yo: { it: 'Yoruba', en: 'Yoruba', es: 'Yoruba', de: 'Yoruba', fr: 'Yoruba', pt: 'Ioruba' },
  zu: { it: 'Zulu', en: 'Zulu', es: 'Zulú', de: 'Zulu', fr: 'Zoulou', pt: 'Zulu' },
  so: { it: 'Somalo', en: 'Somali', es: 'Somalí', de: 'Somali', fr: 'Somali', pt: 'Somali' },
  mg: { it: 'Malgascio', en: 'Malagasy', es: 'Malgache', de: 'Malagasy', fr: 'Malgache', pt: 'Malgaxe' },
  // Altro
  ht: { it: 'Creolo haitiano', en: 'Haitian Creole', es: 'Criollo haitiano', de: 'Haitianisches Kreol', fr: 'Créole haïtien', pt: 'Haitiano' },
  eo: { it: 'Esperanto', en: 'Esperanto', es: 'Esperanto', de: 'Esperanto', fr: 'Espéranto', pt: 'Esperanto' },
};

// Restituisce il nome localizzato di una lingua nella lingua corrente dell'app
export function getLocalizedLanguageName(langCode: string, appLang: AppLanguage): string | undefined {
  return LANGUAGE_NAMES[langCode]?.[appLang];
}
