import { Language } from '../types';

export type RestrictionCategoryId = 'pregnancy' | 'nickel';

export type RestrictionItemId =
  | 'raw_fish'
  | 'raw_cured_meats'
  | 'raw_eggs'
  | 'raw_sprouts'
  | 'unpasteurized_cheese'
  | 'unpasteurized_milk'
  | 'alcohol'
  | 'excessive_caffeine'
  | 'nickel_chocolate'
  | 'nickel_tomato'
  | 'nickel_legumes'
  | 'nickel_nuts'
  | 'nickel_whole_grains'
  | 'nickel_spinach'
  | 'nickel_canned_food'
  | 'nickel_tea_coffee';

export interface RestrictionCategory {
  id: RestrictionCategoryId;
  icon: string;
  translations: Record<Language, string>;
}

export interface RestrictionItem {
  id: RestrictionItemId;
  icon: string;
  categoryId: RestrictionCategoryId;
  translations: Record<Language, string>;
}

export const RESTRICTION_CATEGORIES: readonly RestrictionCategory[] = [
  {
    id: 'pregnancy',
    icon: '🤰',
    translations: {
      it: 'Gravidanza',
      en: 'Pregnancy',
      fr: 'Grossesse',
      de: 'Schwangerschaft',
      es: 'Embarazo',
      pt: 'Gravidez',
      nl: 'Zwangerschap',
      pl: 'Ciąża',
      ru: 'Беременность',
      sv: 'Graviditet',
      zh: '怀孕',
      ja: '妊娠',
      ko: '임신',
      th: 'ตั้งครรภ์',
      ar: 'الحمل',
    },
  },
  {
    id: 'nickel',
    icon: '⚠️',
    translations: {
      it: 'Allergia al nichel',
      en: 'Nickel allergy',
      fr: 'Allergie au nickel',
      de: 'Nickelallergie',
      es: 'Alergia al níquel',
      pt: 'Alergia ao níquel',
      nl: 'Nikkelallergie',
      pl: 'Alergia na nikiel',
      ru: 'Аллергия на никель',
      sv: 'Nickelallergi',
      zh: '镍过敏',
      ja: 'ニッケルアレルギー',
      ko: '니켈 알레르기',
      th: 'แพ้นิกเกิล',
      ar: 'حساسية النيكل',
    },
  },
];

export const RESTRICTION_ITEMS: readonly RestrictionItem[] = [
  // --- Cibi crudi (rischio batteriologico) ---
  {
    id: 'raw_fish',
    icon: '🐟',
    categoryId: 'pregnancy',
    translations: {
      it: 'Pesce crudo / sushi',
      en: 'Raw fish / sushi',
      fr: 'Poisson cru / sushi',
      de: 'Roher Fisch / Sushi',
      es: 'Pescado crudo / sushi',
      pt: 'Peixe cru / sushi',
      nl: 'Rauwe vis / sushi',
      pl: 'Surowa ryba / sushi',
      ru: 'Сырая рыба / суши',
      sv: 'Rå fisk / sushi',
      zh: '生鱼 / 寿司',
      ja: '生魚 / 寿司',
      ko: '생선회 / 초밥',
      th: 'ปลาดิบ / ซูชิ',
      ar: 'السمك النيء / السوشي',
    },
  },
  {
    id: 'raw_cured_meats',
    icon: '🥩',
    categoryId: 'pregnancy',
    translations: {
      it: 'Salumi / affettati crudi',
      en: 'Raw cured meats',
      fr: 'Charcuterie crue',
      de: 'Rohes Pökelfleisch / Aufschnitt',
      es: 'Embutidos / fiambres crudos',
      pt: 'Enchidos / frios crus',
      nl: 'Rauw vleeswaren',
      pl: 'Surowe wędliny',
      ru: 'Сырые мясные деликатесы',
      sv: 'Rått charkuteri',
      zh: '生腌肉 / 冷切肉',
      ja: '生ハム / 生肉加工品',
      ko: '생햄 / 생육가공품',
      th: 'เนื้อหมักดิบ',
      ar: 'اللحوم المقددة النيئة',
    },
  },
  {
    id: 'raw_eggs',
    icon: '🥚',
    categoryId: 'pregnancy',
    translations: {
      it: 'Uova crude',
      en: 'Raw eggs',
      fr: 'Œufs crus',
      de: 'Rohe Eier',
      es: 'Huevos crudos',
      pt: 'Ovos crus',
      nl: 'Rauwe eieren',
      pl: 'Surowe jaja',
      ru: 'Сырые яйца',
      sv: 'Råa ägg',
      zh: '生鸡蛋',
      ja: '生卵',
      ko: '날달걀',
      th: 'ไข่ดิบ',
      ar: 'البيض النيء',
    },
  },
  {
    id: 'raw_sprouts',
    icon: '🌱',
    categoryId: 'pregnancy',
    translations: {
      it: 'Germogli crudi',
      en: 'Raw sprouts',
      fr: 'Germes crus',
      de: 'Rohe Sprossen',
      es: 'Brotes crudos',
      pt: 'Brotos crus',
      nl: 'Rauwe kiemgroenten',
      pl: 'Surowe kiełki',
      ru: 'Сырые ростки',
      sv: 'Råa groddar',
      zh: '生豆芽',
      ja: '生もやし',
      ko: '생 새싹',
      th: 'ถั่วงอกดิบ',
      ar: 'البراعم النيئة',
    },
  },
  // --- Latticini non pastorizzati (rischio listeria) ---
  {
    id: 'unpasteurized_cheese',
    icon: '🧀',
    categoryId: 'pregnancy',
    translations: {
      it: 'Formaggi non pastorizzati',
      en: 'Unpasteurized cheeses',
      fr: 'Fromages non pasteurisés',
      de: 'Nicht pasteurisierter Käse',
      es: 'Quesos no pasteurizados',
      pt: 'Queijos não pasteurizados',
      nl: 'Ongepasteuriseerde kaas',
      pl: 'Sery niepasteryzowane',
      ru: 'Непастеризованные сыры',
      sv: 'Opastöriserad ost',
      zh: '未经巴氏杀菌的奶酪',
      ja: '未殺菌チーズ',
      ko: '비살균 치즈',
      th: 'ชีสที่ไม่ผ่านการพาสเจอร์ไรซ์',
      ar: 'الأجبان غير المبسترة',
    },
  },
  {
    id: 'unpasteurized_milk',
    icon: '🥛',
    categoryId: 'pregnancy',
    translations: {
      it: 'Latte non pastorizzato',
      en: 'Unpasteurized milk',
      fr: 'Lait non pasteurisé',
      de: 'Nicht pasteurisierte Milch',
      es: 'Leche no pasteurizada',
      pt: 'Leite não pasteurizado',
      nl: 'Ongepasteuriseerde melk',
      pl: 'Mleko niepasteryzowane',
      ru: 'Непастеризованное молоко',
      sv: 'Opastöriserad mjölk',
      zh: '未经巴氏杀菌的牛奶',
      ja: '未殺菌牛乳',
      ko: '비살균 우유',
      th: 'นมที่ไม่ผ่านการพาสเจอร์ไรซ์',
      ar: 'الحليب غير المبستر',
    },
  },
  // --- Sostanze da evitare/limitare ---
  {
    id: 'alcohol',
    icon: '🍷',
    categoryId: 'pregnancy',
    translations: {
      it: 'Alcol',
      en: 'Alcohol',
      fr: 'Alcool',
      de: 'Alkohol',
      es: 'Alcohol',
      pt: 'Álcool',
      nl: 'Alcohol',
      pl: 'Alkohol',
      ru: 'Алкоголь',
      sv: 'Alkohol',
      zh: '酒精',
      ja: 'アルコール',
      ko: '알코올',
      th: 'แอลกอฮอล์',
      ar: 'الكحول',
    },
  },
  {
    id: 'excessive_caffeine',
    icon: '☕',
    categoryId: 'pregnancy',
    translations: {
      it: 'Caffeina eccessiva',
      en: 'Excessive caffeine',
      fr: 'Caféine excessive',
      de: 'Übermäßiges Koffein',
      es: 'Cafeína excesiva',
      pt: 'Cafeína excessiva',
      nl: 'Overmatig cafeïne',
      pl: 'Nadmierna kofeina',
      ru: 'Избыток кофеина',
      sv: 'Överdrivet koffein',
      zh: '过量咖啡因',
      ja: '過剰なカフェイン',
      ko: '과도한 카페인',
      th: 'คาเฟอีนมากเกินไป',
      ar: 'الكافيين المفرط',
    },
  },
  // --- Allergia al nichel (cibi ad alto contenuto) ---
  {
    id: 'nickel_chocolate',
    icon: '🍫',
    categoryId: 'nickel',
    translations: {
      it: 'Cioccolato / cacao',
      en: 'Chocolate / cocoa',
      fr: 'Chocolat / cacao',
      de: 'Schokolade / Kakao',
      es: 'Chocolate / cacao',
      pt: 'Chocolate / cacau',
      nl: 'Chocolade / cacao',
      pl: 'Czekolada / kakao',
      ru: 'Шоколад / какао',
      sv: 'Choklad / kakao',
      zh: '巧克力 / 可可',
      ja: 'チョコレート / ココア',
      ko: '초콜릿 / 코코아',
      th: 'ช็อกโกแลต / โกโก้',
      ar: 'الشوكولاتة / الكاكاو',
    },
  },
  {
    id: 'nickel_tomato',
    icon: '🍅',
    categoryId: 'nickel',
    translations: {
      it: 'Pomodoro e salse di pomodoro',
      en: 'Tomato and tomato sauces',
      fr: 'Tomate et sauces tomate',
      de: 'Tomate und Tomatensoßen',
      es: 'Tomate y salsas de tomate',
      pt: 'Tomate e molhos de tomate',
      nl: 'Tomaat en tomatensauzen',
      pl: 'Pomidor i sosy pomidorowe',
      ru: 'Помидоры и томатные соусы',
      sv: 'Tomat och tomatsåser',
      zh: '番茄和番茄酱',
      ja: 'トマトとトマトソース',
      ko: '토마토와 토마토소스',
      th: 'มะเขือเทศและซอสมะเขือเทศ',
      ar: 'الطماطم وصلصات الطماطم',
    },
  },
  {
    id: 'nickel_legumes',
    icon: '🫘',
    categoryId: 'nickel',
    translations: {
      it: 'Legumi (lenticchie, ceci, fagioli)',
      en: 'Legumes (lentils, chickpeas, beans)',
      fr: 'Légumineuses (lentilles, pois chiches, haricots)',
      de: 'Hülsenfrüchte (Linsen, Kichererbsen, Bohnen)',
      es: 'Legumbres (lentejas, garbanzos, judías)',
      pt: 'Leguminosas (lentilhas, grão-de-bico, feijão)',
      nl: 'Peulvruchten (linzen, kikkererwten, bonen)',
      pl: 'Rośliny strączkowe (soczewica, ciecierzyca, fasola)',
      ru: 'Бобовые (чечевица, нут, фасоль)',
      sv: 'Baljväxter (linser, kikärtor, bönor)',
      zh: '豆类（扁豆、鹰嘴豆、豆子）',
      ja: '豆類（レンズ豆、ひよこ豆、インゲン豆）',
      ko: '콩류 (렌틸콩, 병아리콩, 강낭콩)',
      th: 'ถั่ว (ถั่วเลนทิล, ถั่วลูกไก่, ถั่วแดง)',
      ar: 'البقوليات (العدس، الحمص، الفاصوليا)',
    },
  },
  {
    id: 'nickel_nuts',
    icon: '🥜',
    categoryId: 'nickel',
    translations: {
      it: 'Frutta a guscio (noci, nocciole, anacardi)',
      en: 'Nuts (walnuts, hazelnuts, cashews)',
      fr: 'Fruits à coque (noix, noisettes, cajous)',
      de: 'Nüsse (Walnüsse, Haselnüsse, Cashews)',
      es: 'Frutos secos (nueces, avellanas, anacardos)',
      pt: 'Frutos secos (nozes, avelãs, cajus)',
      nl: 'Noten (walnoten, hazelnoten, cashewnoten)',
      pl: 'Orzechy (włoskie, laskowe, nerkowce)',
      ru: 'Орехи (грецкие, фундук, кешью)',
      sv: 'Nötter (valnötter, hasselnötter, cashewnötter)',
      zh: '坚果（核桃、榛子、腰果）',
      ja: 'ナッツ類（クルミ、ヘーゼルナッツ、カシューナッツ）',
      ko: '견과류 (호두, 헤이즐넛, 캐슈넛)',
      th: 'ถั่วเปลือกแข็ง (วอลนัท, เฮเซลนัท, มะม่วงหิมพานต์)',
      ar: 'المكسرات (الجوز، البندق، الكاجو)',
    },
  },
  {
    id: 'nickel_whole_grains',
    icon: '🌾',
    categoryId: 'nickel',
    translations: {
      it: 'Cereali integrali / avena',
      en: 'Whole grains / oats',
      fr: 'Céréales complètes / avoine',
      de: 'Vollkorngetreide / Hafer',
      es: 'Cereales integrales / avena',
      pt: 'Cereais integrais / aveia',
      nl: 'Volkoren granen / haver',
      pl: 'Pełne ziarna / owies',
      ru: 'Цельнозерновые / овёс',
      sv: 'Fullkorn / havre',
      zh: '全谷物 / 燕麦',
      ja: '全粒穀物 / オーツ麦',
      ko: '통곡물 / 귀리',
      th: 'ธัญพืชเต็มเมล็ด / ข้าวโอ๊ต',
      ar: 'الحبوب الكاملة / الشوفان',
    },
  },
  {
    id: 'nickel_spinach',
    icon: '🥬',
    categoryId: 'nickel',
    translations: {
      it: 'Spinaci e verdure a foglia verde',
      en: 'Spinach and leafy greens',
      fr: 'Épinards et légumes-feuilles',
      de: 'Spinat und Blattgemüse',
      es: 'Espinacas y verduras de hoja verde',
      pt: 'Espinafre e verduras de folha',
      nl: 'Spinazie en bladgroenten',
      pl: 'Szpinak i warzywa liściaste',
      ru: 'Шпинат и листовая зелень',
      sv: 'Spenat och bladgrönsaker',
      zh: '菠菜和绿叶蔬菜',
      ja: 'ほうれん草と葉野菜',
      ko: '시금치와 잎채소',
      th: 'ผักโขมและผักใบเขียว',
      ar: 'السبانخ والخضروات الورقية',
    },
  },
  {
    id: 'nickel_canned_food',
    icon: '🥫',
    categoryId: 'nickel',
    translations: {
      it: 'Cibi in scatola / lattina',
      en: 'Canned food',
      fr: 'Aliments en conserve',
      de: 'Konserven / Dosenkost',
      es: 'Alimentos enlatados',
      pt: 'Alimentos enlatados',
      nl: 'Ingeblikt voedsel',
      pl: 'Żywność w puszkach',
      ru: 'Консервированная еда',
      sv: 'Konserverad mat',
      zh: '罐头食品',
      ja: '缶詰食品',
      ko: '통조림 식품',
      th: 'อาหารกระป๋อง',
      ar: 'الأطعمة المعلبة',
    },
  },
  {
    id: 'nickel_tea_coffee',
    icon: '☕',
    categoryId: 'nickel',
    translations: {
      it: 'Tè e caffè',
      en: 'Tea and coffee',
      fr: 'Thé et café',
      de: 'Tee und Kaffee',
      es: 'Té y café',
      pt: 'Chá e café',
      nl: 'Thee en koffie',
      pl: 'Herbata i kawa',
      ru: 'Чай и кофе',
      sv: 'Te och kaffe',
      zh: '茶和咖啡',
      ja: 'お茶とコーヒー',
      ko: '차와 커피',
      th: 'ชาและกาแฟ',
      ar: 'الشاي والقهوة',
    },
  },
];

export const getRestrictionItemsByCategory = (categoryId: RestrictionCategoryId): RestrictionItem[] => {
  return RESTRICTION_ITEMS.filter((r) => r.categoryId === categoryId);
};
