import type { RestaurantCategory } from '../types';

// Filtri dietetici — sempre visibili nella lista ristoranti
export const RESTAURANT_CATEGORIES: RestaurantCategory[] = [
  {
    id: 'gluten_free',
    icon: '🌾',
    translations: {
      it: 'Gluten Free',
      en: 'Gluten Free',
      fr: 'Sans gluten',
      de: 'Glutenfrei',
      es: 'Sin gluten',
      pt: 'Sem glúten',
      nl: 'Glutenvrij',
      pl: 'Bezglutenowe',
      ru: 'Без глютена',
      sv: 'Glutenfritt',
      zh: '无麸质',
      ja: 'グルテンフリー',
      ko: '글루텐 프리',
      th: 'ปราศจากกลูเตน',
      ar: 'خالٍ من الغلوتين',
    },
  },
  {
    id: 'vegan',
    icon: '🌱',
    translations: {
      it: 'Vegan',
      en: 'Vegan',
      fr: 'Vegan',
      de: 'Vegan',
      es: 'Vegan',
      pt: 'Vegan',
      nl: 'Vegan',
      pl: 'Vegan',
      ru: 'Vegan',
      sv: 'Vegan',
      zh: 'Vegan',
      ja: 'Vegan',
      ko: 'Vegan',
      th: 'Vegan',
      ar: 'Vegan',
    },
  },
  {
    id: 'vegetarian',
    icon: '🥬',
    translations: {
      it: 'Vegetarian',
      en: 'Vegetarian',
      fr: 'Vegetarian',
      de: 'Vegetarian',
      es: 'Vegetarian',
      pt: 'Vegetarian',
      nl: 'Vegetarian',
      pl: 'Vegetarian',
      ru: 'Vegetarian',
      sv: 'Vegetarian',
      zh: 'Vegetarian',
      ja: 'Vegetarian',
      ko: 'Vegetarian',
      th: 'Vegetarian',
      ar: 'Vegetarian',
    },
  },
];

// Filtri tipo di cucina — in pannello espandibile
// Ordine: più cercate prima, poi per area geografica
export const CUISINE_CATEGORIES: RestaurantCategory[] = [
  {
    id: 'pizza',
    icon: '🍕',
    translations: {
      it: 'Pizza',
      en: 'Pizza',
      fr: 'Pizza',
      de: 'Pizza',
      es: 'Pizza',
      pt: 'Pizza',
      nl: 'Pizza',
      pl: 'Pizza',
      ru: 'Пицца',
      sv: 'Pizza',
      zh: '披萨',
      ja: 'ピザ',
      ko: '피자',
      th: 'พิซซ่า',
      ar: 'بيتزا',
    },
  },
  {
    id: 'sushi',
    icon: '🍣',
    translations: {
      it: 'Sushi',
      en: 'Sushi',
      fr: 'Sushi',
      de: 'Sushi',
      es: 'Sushi',
      pt: 'Sushi',
      nl: 'Sushi',
      pl: 'Sushi',
      ru: 'Суши',
      sv: 'Sushi',
      zh: '寿司',
      ja: '寿司',
      ko: '스시',
      th: 'ซูชิ',
      ar: 'سوشي',
    },
  },
  {
    id: 'hamburger',
    icon: '🍔',
    translations: {
      it: 'Hamburger',
      en: 'Hamburger',
      fr: 'Hamburger',
      de: 'Hamburger',
      es: 'Hamburguesa',
      pt: 'Hambúrguer',
      nl: 'Hamburger',
      pl: 'Hamburger',
      ru: 'Гамбургер',
      sv: 'Hamburgare',
      zh: '汉堡',
      ja: 'ハンバーガー',
      ko: '햄버거',
      th: 'แฮมเบอร์เกอร์',
      ar: 'هامبرغر',
    },
  },
  {
    id: 'italian',
    icon: '🇮🇹',
    translations: {
      it: 'Italiana',
      en: 'Italian',
      fr: 'Italienne',
      de: 'Italienisch',
      es: 'Italiana',
      pt: 'Italiana',
      nl: 'Italiaans',
      pl: 'Włoska',
      ru: 'Итальянская',
      sv: 'Italiensk',
      zh: '意大利菜',
      ja: 'イタリアン',
      ko: '이탈리안',
      th: 'อิตาเลียน',
      ar: 'إيطالي',
    },
  },
  {
    id: 'japanese',
    icon: '🇯🇵',
    translations: {
      it: 'Giapponese',
      en: 'Japanese',
      fr: 'Japonaise',
      de: 'Japanisch',
      es: 'Japonesa',
      pt: 'Japonesa',
      nl: 'Japans',
      pl: 'Japońska',
      ru: 'Японская',
      sv: 'Japansk',
      zh: '日本料理',
      ja: '和食',
      ko: '일식',
      th: 'ญี่ปุ่น',
      ar: 'ياباني',
    },
  },
  {
    id: 'chinese',
    icon: '🇨🇳',
    translations: {
      it: 'Cinese',
      en: 'Chinese',
      fr: 'Chinoise',
      de: 'Chinesisch',
      es: 'China',
      pt: 'Chinesa',
      nl: 'Chinees',
      pl: 'Chińska',
      ru: 'Китайская',
      sv: 'Kinesisk',
      zh: '中餐',
      ja: '中華',
      ko: '중식',
      th: 'จีน',
      ar: 'صيني',
    },
  },
  {
    id: 'thai',
    icon: '🇹🇭',
    translations: {
      it: 'Thailandese',
      en: 'Thai',
      fr: 'Thaïlandaise',
      de: 'Thailändisch',
      es: 'Tailandesa',
      pt: 'Tailandesa',
      nl: 'Thais',
      pl: 'Tajska',
      ru: 'Тайская',
      sv: 'Thailändsk',
      zh: '泰国菜',
      ja: 'タイ料理',
      ko: '태국',
      th: 'ไทย',
      ar: 'تايلاندي',
    },
  },
  {
    id: 'mexican',
    icon: '🇲🇽',
    translations: {
      it: 'Messicana',
      en: 'Mexican',
      fr: 'Mexicaine',
      de: 'Mexikanisch',
      es: 'Mexicana',
      pt: 'Mexicana',
      nl: 'Mexicaans',
      pl: 'Meksykańska',
      ru: 'Мексиканская',
      sv: 'Mexikansk',
      zh: '墨西哥菜',
      ja: 'メキシカン',
      ko: '멕시칸',
      th: 'เม็กซิกัน',
      ar: 'مكسيكي',
    },
  },
  {
    id: 'indian',
    icon: '🇮🇳',
    translations: {
      it: 'Indiana',
      en: 'Indian',
      fr: 'Indienne',
      de: 'Indisch',
      es: 'India',
      pt: 'Indiana',
      nl: 'Indiaas',
      pl: 'Indyjska',
      ru: 'Индийская',
      sv: 'Indisk',
      zh: '印度菜',
      ja: 'インド料理',
      ko: '인도',
      th: 'อินเดีย',
      ar: 'هندي',
    },
  },
  {
    id: 'korean',
    icon: '🇰🇷',
    translations: {
      it: 'Coreana',
      en: 'Korean',
      fr: 'Coréenne',
      de: 'Koreanisch',
      es: 'Coreana',
      pt: 'Coreana',
      nl: 'Koreaans',
      pl: 'Koreańska',
      ru: 'Корейская',
      sv: 'Koreansk',
      zh: '韩国菜',
      ja: '韓国料理',
      ko: '한식',
      th: 'เกาหลี',
      ar: 'كوري',
    },
  },
  {
    id: 'mediterranean',
    icon: '🫒',
    translations: {
      it: 'Mediterranea',
      en: 'Mediterranean',
      fr: 'Méditerranéenne',
      de: 'Mediterran',
      es: 'Mediterránea',
      pt: 'Mediterrânea',
      nl: 'Mediterraans',
      pl: 'Śródziemnomorska',
      ru: 'Средиземноморская',
      sv: 'Medelhavs',
      zh: '地中海',
      ja: '地中海料理',
      ko: '지중해',
      th: 'เมดิเตอร์เรเนียน',
      ar: 'متوسطي',
    },
  },
  {
    id: 'greek',
    icon: '🇬🇷',
    translations: {
      it: 'Greca',
      en: 'Greek',
      fr: 'Grecque',
      de: 'Griechisch',
      es: 'Griega',
      pt: 'Grega',
      nl: 'Grieks',
      pl: 'Grecka',
      ru: 'Греческая',
      sv: 'Grekisk',
      zh: '希腊菜',
      ja: 'ギリシャ料理',
      ko: '그리스',
      th: 'กรีก',
      ar: 'يوناني',
    },
  },
  {
    id: 'turkish',
    icon: '🇹🇷',
    translations: {
      it: 'Turca',
      en: 'Turkish',
      fr: 'Turque',
      de: 'Türkisch',
      es: 'Turca',
      pt: 'Turca',
      nl: 'Turks',
      pl: 'Turecka',
      ru: 'Турецкая',
      sv: 'Turkisk',
      zh: '土耳其菜',
      ja: 'トルコ料理',
      ko: '터키',
      th: 'ตุรกี',
      ar: 'تركي',
    },
  },
  {
    id: 'arabic',
    icon: '🧆',
    translations: {
      it: 'Araba',
      en: 'Arabic',
      fr: 'Arabe',
      de: 'Arabisch',
      es: 'Árabe',
      pt: 'Árabe',
      nl: 'Arabisch',
      pl: 'Arabska',
      ru: 'Арабская',
      sv: 'Arabisk',
      zh: '阿拉伯菜',
      ja: 'アラビア料理',
      ko: '아랍',
      th: 'อาหรับ',
      ar: 'عربي',
    },
  },
  {
    id: 'french',
    icon: '🇫🇷',
    translations: {
      it: 'Francese',
      en: 'French',
      fr: 'Française',
      de: 'Französisch',
      es: 'Francesa',
      pt: 'Francesa',
      nl: 'Frans',
      pl: 'Francuska',
      ru: 'Французская',
      sv: 'Fransk',
      zh: '法国菜',
      ja: 'フレンチ',
      ko: '프랑스',
      th: 'ฝรั่งเศส',
      ar: 'فرنسي',
    },
  },
  {
    id: 'spanish',
    icon: '🇪🇸',
    translations: {
      it: 'Spagnola',
      en: 'Spanish',
      fr: 'Espagnole',
      de: 'Spanisch',
      es: 'Española',
      pt: 'Espanhola',
      nl: 'Spaans',
      pl: 'Hiszpańska',
      ru: 'Испанская',
      sv: 'Spansk',
      zh: '西班牙菜',
      ja: 'スペイン料理',
      ko: '스페인',
      th: 'สเปน',
      ar: 'إسباني',
    },
  },
  {
    id: 'brazilian',
    icon: '🇧🇷',
    translations: {
      it: 'Brasiliana',
      en: 'Brazilian',
      fr: 'Brésilienne',
      de: 'Brasilianisch',
      es: 'Brasileña',
      pt: 'Brasileira',
      nl: 'Braziliaans',
      pl: 'Brazylijska',
      ru: 'Бразильская',
      sv: 'Brasiliansk',
      zh: '巴西菜',
      ja: 'ブラジル料理',
      ko: '브라질',
      th: 'บราซิล',
      ar: 'برازيلي',
    },
  },
  {
    id: 'peruvian',
    icon: '🇵🇪',
    translations: {
      it: 'Peruviana',
      en: 'Peruvian',
      fr: 'Péruvienne',
      de: 'Peruanisch',
      es: 'Peruana',
      pt: 'Peruana',
      nl: 'Peruaans',
      pl: 'Peruwiańska',
      ru: 'Перуанская',
      sv: 'Peruansk',
      zh: '秘鲁菜',
      ja: 'ペルー料理',
      ko: '페루',
      th: 'เปรู',
      ar: 'بيروفي',
    },
  },
];

// Tutte le categorie combinate — usata per lookup nei card/dettagli
export const ALL_RESTAURANT_CATEGORIES: RestaurantCategory[] = [
  ...RESTAURANT_CATEGORIES,
  ...CUISINE_CATEGORIES,
];
