import type { RestaurantCategory, LodgingCategory, LodgingTypeId } from '../types';

// Filtri dietetici — sempre visibili nella lista ristoranti
export const RESTAURANT_CATEGORIES: RestaurantCategory[] = [
  {
    id: 'gluten_free',
    translations: {
      it: 'Gluten Free',
      en: 'Gluten Free',
      fr: 'Sans gluten',
      de: 'Glutenfrei',
      es: 'Sin gluten',
      pt: 'Sem glúten',
      nl: 'Glutenvrij',
      pl: 'Bezglutenowe',
      ru: 'Без глютена',
      sv: 'Glutenfritt',
      zh: '无麸质',
      ja: 'グルテンフリー',
      ko: '글루텐 프리',
      th: 'ปราศจากกลูเตน',
      ar: 'خالٍ من الغلوتين',
    },
  },
  {
    id: 'vegan',
    translations: {
      it: 'Vegan',
      en: 'Vegan',
      fr: 'Vegan',
      de: 'Vegan',
      es: 'Vegan',
      pt: 'Vegan',
      nl: 'Vegan',
      pl: 'Vegan',
      ru: 'Vegan',
      sv: 'Vegan',
      zh: 'Vegan',
      ja: 'Vegan',
      ko: 'Vegan',
      th: 'Vegan',
      ar: 'Vegan',
    },
  },
  {
    id: 'vegetarian',
    translations: {
      it: 'Vegetariano',
      en: 'Vegetarian',
      fr: 'Végétarien',
      de: 'Vegetarisch',
      es: 'Vegetariano',
      pt: 'Vegetariano',
      nl: 'Vegetarisch',
      pl: 'Wegetariańskie',
      ru: 'Вегетарианское',
      sv: 'Vegetariskt',
      zh: '素食',
      ja: 'ベジタリアン',
      ko: '채식',
      th: 'มังสวิรัติ',
      ar: 'نباتي',
    },
  },
];

// Filtri tipo di cucina — in pannello espandibile
export const CUISINE_CATEGORIES: RestaurantCategory[] = [
  {
    id: 'italian',
    translations: {
      it: 'Italiana',
      en: 'Italian',
      fr: 'Italienne',
      de: 'Italienisch',
      es: 'Italiana',
      pt: 'Italiana',
      nl: 'Italiaans',
      pl: 'Włoska',
      ru: 'Итальянская',
      sv: 'Italiensk',
      zh: '意大利菜',
      ja: 'イタリアン',
      ko: '이탈리안',
      th: 'อิตาเลียน',
      ar: 'إيطالي',
    },
  },
  {
    id: 'pizza',
    translations: {
      it: 'Pizza',
      en: 'Pizza',
      fr: 'Pizza',
      de: 'Pizza',
      es: 'Pizza',
      pt: 'Pizza',
      nl: 'Pizza',
      pl: 'Pizza',
      ru: 'Пицца',
      sv: 'Pizza',
      zh: '披萨',
      ja: 'ピザ',
      ko: '피자',
      th: 'พิซซ่า',
      ar: 'بيتزا',
    },
  },
  {
    id: 'french',
    translations: {
      it: 'Francese',
      en: 'French',
      fr: 'Française',
      de: 'Französisch',
      es: 'Francesa',
      pt: 'Francesa',
      nl: 'Frans',
      pl: 'Francuska',
      ru: 'Французская',
      sv: 'Fransk',
      zh: '法国菜',
      ja: 'フランス料理',
      ko: '프랑스',
      th: 'ฝรั่งเศส',
      ar: 'فرنسي',
    },
  },
  {
    id: 'spanish',
    translations: {
      it: 'Spagnola',
      en: 'Spanish',
      fr: 'Espagnole',
      de: 'Spanisch',
      es: 'Española',
      pt: 'Espanhola',
      nl: 'Spaans',
      pl: 'Hiszpańska',
      ru: 'Испанская',
      sv: 'Spansk',
      zh: '西班牙菜',
      ja: 'スペイン料理',
      ko: '스페인',
      th: 'สเปน',
      ar: 'إسباني',
    },
  },
  {
    id: 'mediterranean',
    translations: {
      it: 'Mediterranea',
      en: 'Mediterranean',
      fr: 'Méditerranéenne',
      de: 'Mediterran',
      es: 'Mediterránea',
      pt: 'Mediterrânea',
      nl: 'Mediterraans',
      pl: 'Śródziemnomorska',
      ru: 'Средиземноморская',
      sv: 'Medelhavs',
      zh: '地中海',
      ja: '地中海料理',
      ko: '지중해',
      th: 'เมดิเตอร์เรเนียน',
      ar: 'متوسطي',
    },
  },
  {
    id: 'meat_grill',
    translations: {
      it: 'Carne e grigliate',
      en: 'Meat & Grill',
      fr: 'Viande et grillades',
      de: 'Fleisch & Grill',
      es: 'Carne y parrilla',
      pt: 'Carne e grelhados',
      nl: 'Vlees & Grill',
      pl: 'Mięso i grillowane',
      ru: 'Мясо и гриль',
      sv: 'Kött & Grill',
      zh: '肉类与烧烤',
      ja: '肉料理・グリル',
      ko: '고기 & 그릴',
      th: 'เนื้อและย่าง',
      ar: 'لحوم ومشويات',
    },
  },
  {
    id: 'seafood',
    translations: {
      it: 'Pesce e frutti di mare',
      en: 'Seafood',
      fr: 'Poissons et fruits de mer',
      de: 'Meeresfrüchte',
      es: 'Mariscos y pescados',
      pt: 'Frutos do mar',
      nl: 'Zeevruchten',
      pl: 'Owoce morza',
      ru: 'Морепродукты',
      sv: 'Skaldjur',
      zh: '海鲜',
      ja: '海鮮料理',
      ko: '해산물',
      th: 'อาหารทะเล',
      ar: 'مأكولات بحرية',
    },
  },
  {
    id: 'hamburger',
    translations: {
      it: 'Hamburger e panini',
      en: 'Burgers & Sandwiches',
      fr: 'Burgers et sandwichs',
      de: 'Burger & Sandwiches',
      es: 'Hamburguesas y bocadillos',
      pt: 'Hambúrgueres e sanduíches',
      nl: 'Burgers & Sandwiches',
      pl: 'Burgery i kanapki',
      ru: 'Бургеры и сэндвичи',
      sv: 'Burgare & Smörgåsar',
      zh: '汉堡与三明治',
      ja: 'バーガー・サンドイッチ',
      ko: '버거 & 샌드위치',
      th: 'เบอร์เกอร์และแซนด์วิช',
      ar: 'برغر وسندويشات',
    },
  },
  {
    id: 'sushi',
    translations: {
      it: 'Sushi',
      en: 'Sushi',
      fr: 'Sushi',
      de: 'Sushi',
      es: 'Sushi',
      pt: 'Sushi',
      nl: 'Sushi',
      pl: 'Sushi',
      ru: 'Суши',
      sv: 'Sushi',
      zh: '寿司',
      ja: '寿司',
      ko: '스시',
      th: 'ซูชิ',
      ar: 'سوشي',
    },
  },
  {
    id: 'japanese',
    translations: {
      it: 'Giapponese',
      en: 'Japanese',
      fr: 'Japonaise',
      de: 'Japanisch',
      es: 'Japonesa',
      pt: 'Japonesa',
      nl: 'Japans',
      pl: 'Japońska',
      ru: 'Японская',
      sv: 'Japansk',
      zh: '日本料理',
      ja: '和食',
      ko: '일식',
      th: 'ญี่ปุ่น',
      ar: 'ياباني',
    },
  },
  {
    id: 'chinese',
    translations: {
      it: 'Cinese',
      en: 'Chinese',
      fr: 'Chinoise',
      de: 'Chinesisch',
      es: 'China',
      pt: 'Chinesa',
      nl: 'Chinees',
      pl: 'Chińska',
      ru: 'Китайская',
      sv: 'Kinesisk',
      zh: '中餐',
      ja: '中華',
      ko: '중식',
      th: 'จีน',
      ar: 'صيني',
    },
  },
  {
    id: 'korean',
    translations: {
      it: 'Coreana',
      en: 'Korean',
      fr: 'Coréenne',
      de: 'Koreanisch',
      es: 'Coreana',
      pt: 'Coreana',
      nl: 'Koreaans',
      pl: 'Koreańska',
      ru: 'Корейская',
      sv: 'Koreansk',
      zh: '韩国菜',
      ja: '韓国料理',
      ko: '한식',
      th: 'เกาหลี',
      ar: 'كوري',
    },
  },
  {
    id: 'vietnamese',
    translations: {
      it: 'Vietnamita',
      en: 'Vietnamese',
      fr: 'Vietnamienne',
      de: 'Vietnamesisch',
      es: 'Vietnamita',
      pt: 'Vietnamita',
      nl: 'Vietnamees',
      pl: 'Wietnamska',
      ru: 'Вьетнамская',
      sv: 'Vietnamesisk',
      zh: '越南菜',
      ja: 'ベトナム料理',
      ko: '베트남',
      th: 'เวียดนาม',
      ar: 'فيتنامي',
    },
  },
  {
    id: 'thai',
    translations: {
      it: 'Thailandese',
      en: 'Thai',
      fr: 'Thaïlandaise',
      de: 'Thailändisch',
      es: 'Tailandesa',
      pt: 'Tailandesa',
      nl: 'Thais',
      pl: 'Tajska',
      ru: 'Тайская',
      sv: 'Thailändsk',
      zh: '泰国菜',
      ja: 'タイ料理',
      ko: '태국',
      th: 'ไทย',
      ar: 'تايلاندي',
    },
  },
  {
    id: 'indian',
    translations: {
      it: 'Indiana',
      en: 'Indian',
      fr: 'Indienne',
      de: 'Indisch',
      es: 'India',
      pt: 'Indiana',
      nl: 'Indiaas',
      pl: 'Indyjska',
      ru: 'Индийская',
      sv: 'Indisk',
      zh: '印度菜',
      ja: 'インド料理',
      ko: '인도',
      th: 'อินเดีย',
      ar: 'هندي',
    },
  },
  {
    id: 'middle_eastern',
    translations: {
      it: 'Arabo e mediorientale',
      en: 'Middle Eastern & Arabic',
      fr: 'Arabe et moyen-oriental',
      de: 'Arabisch & Nahöstlich',
      es: 'Árabe y oriente medio',
      pt: 'Árabe e médio-oriental',
      nl: 'Arabisch & Midden-Oosters',
      pl: 'Arabska i bliskowschodnia',
      ru: 'Арабская и ближневосточная',
      sv: 'Arabisk & Mellanöstern',
      zh: '阿拉伯与中东',
      ja: 'アラブ・中東料理',
      ko: '아랍 & 중동',
      th: 'อาหรับและตะวันออกกลาง',
      ar: 'عربي وشرق أوسطي',
    },
  },
  {
    id: 'mexican',
    translations: {
      it: 'Messicana',
      en: 'Mexican',
      fr: 'Mexicaine',
      de: 'Mexikanisch',
      es: 'Mexicana',
      pt: 'Mexicana',
      nl: 'Mexicaans',
      pl: 'Meksykańska',
      ru: 'Мексиканская',
      sv: 'Mexikansk',
      zh: '墨西哥菜',
      ja: 'メキシカン',
      ko: '멕시칸',
      th: 'เม็กซิกัน',
      ar: 'مكسيكي',
    },
  },
  {
    id: 'latin_american',
    translations: {
      it: 'Latino americana',
      en: 'Latin American',
      fr: 'Latino-américaine',
      de: 'Lateinamerikanisch',
      es: 'Latinoamericana',
      pt: 'Latino-americana',
      nl: 'Latijns-Amerikaans',
      pl: 'Latynoamerykańska',
      ru: 'Латиноамериканская',
      sv: 'Latinamerikansk',
      zh: '拉丁美洲菜',
      ja: 'ラテンアメリカ料理',
      ko: '라틴아메리카',
      th: 'ละตินอเมริกา',
      ar: 'أمريكا اللاتينية',
    },
  },
  {
    id: 'bakery',
    translations: {
      it: 'Bakery',
      en: 'Bakery',
      fr: 'Bakery',
      de: 'Bakery',
      es: 'Bakery',
      pt: 'Bakery',
      nl: 'Bakery',
      pl: 'Bakery',
      ru: 'Bakery',
      sv: 'Bakery',
      zh: 'Bakery',
      ja: 'Bakery',
      ko: 'Bakery',
      th: 'Bakery',
      ar: 'Bakery',
    },
  },
  {
    id: 'cafe',
    translations: {
      it: 'Caffè e bar',
      en: 'Café & Bar',
      fr: 'Café et bar',
      de: 'Café & Bar',
      es: 'Café y bar',
      pt: 'Café e bar',
      nl: 'Café & Bar',
      pl: 'Kawiarnia i bar',
      ru: 'Кафе и бар',
      sv: 'Kafé & Bar',
      zh: '咖啡厅与酒吧',
      ja: 'カフェ・バー',
      ko: '카페 & 바',
      th: 'คาเฟ่และบาร์',
      ar: 'مقهى وبار',
    },
  },
  {
    id: 'ice_cream',
    translations: {
      it: 'Gelateria',
      en: 'Ice Cream & Gelato',
      fr: 'Glaces et gelato',
      de: 'Eisdiele',
      es: 'Heladería',
      pt: 'Sorveteria',
      nl: 'IJssalon',
      pl: 'Lodziarnia',
      ru: 'Мороженое',
      sv: 'Glasskiosk',
      zh: '冰淇淋店',
      ja: 'アイスクリーム・ジェラート',
      ko: '아이스크림 & 젤라또',
      th: 'ไอศกรีมและเจลาโต้',
      ar: 'آيس كريم وجيلاتو',
    },
  },
];

// Tutte le categorie combinate — usata per lookup nei card/dettagli
export const ALL_RESTAURANT_CATEGORIES: RestaurantCategory[] = [
  ...RESTAURANT_CATEGORIES,
  ...CUISINE_CATEGORIES,
];

// Lookup O(1) per id → categoria
const CATEGORY_MAP = new Map(ALL_RESTAURANT_CATEGORIES.map(c => [c.id, c]));

/** Restituisce la label tradotta per un id categoria dato una lingua */
export function getCuisineLabel(id: string, lang: string = 'it'): string {
  const cat = CATEGORY_MAP.get(id as RestaurantCategory['id']);
  if (!cat) return id;
  return cat.translations[lang as keyof typeof cat.translations] ?? cat.translations.it;
}

/** Restituisce array di label tradotte per un array di id */
export function getCuisineLabels(ids: string[], lang: string = 'it'): string[] {
  return ids.map(id => getCuisineLabel(id, lang));
}

// ─── Tipi struttura ricettiva (faccetta lodging) ─────────────────────────────
// Asse separato dalle categorie ristorante. Le label sono PRIMA PASSATA: hotel/
// B&B/guest house sono forme internazionali (loanword come Bakery/Sushi); per
// hostel/agriturismo/apartment le lingue CJK/TH/AR vanno riviste da madrelingua.
export const ACCOMMODATION_CATEGORIES: LodgingCategory[] = [
  {
    id: 'hotel',
    translations: {
      it: 'Hotel', en: 'Hotel', fr: 'Hôtel', de: 'Hotel', es: 'Hotel',
      pt: 'Hotel', nl: 'Hotel', pl: 'Hotel', ru: 'Отель', sv: 'Hotell',
      zh: '酒店', ja: 'ホテル', ko: '호텔', th: 'โรงแรม', ar: 'فندق',
    },
  },
  {
    id: 'bnb',
    translations: {
      it: 'B&B', en: 'B&B', fr: 'B&B', de: 'B&B', es: 'B&B',
      pt: 'B&B', nl: 'B&B', pl: 'B&B', ru: 'B&B', sv: 'B&B',
      zh: 'B&B', ja: 'B&B', ko: 'B&B', th: 'B&B', ar: 'B&B',
    },
  },
  {
    id: 'guest_house',
    translations: {
      it: 'Guest house', en: 'Guest house', fr: 'Guest house', de: 'Guest house', es: 'Guest house',
      pt: 'Guest house', nl: 'Guest house', pl: 'Guest house', ru: 'Guest house', sv: 'Guest house',
      zh: 'Guest house', ja: 'Guest house', ko: 'Guest house', th: 'Guest house', ar: 'Guest house',
    },
  },
  {
    id: 'hostel',
    translations: {
      it: 'Ostello', en: 'Hostel', fr: 'Auberge de jeunesse', de: 'Hostel', es: 'Hostal',
      pt: 'Hostel', nl: 'Hostel', pl: 'Hostel', ru: 'Хостел', sv: 'Vandrarhem',
      zh: '青年旅舍', ja: 'ホステル', ko: '호스텔', th: 'โฮสเทล', ar: 'نُزُل',
    },
  },
  {
    id: 'agriturismo',
    translations: {
      it: 'Agriturismo', en: 'Farm stay', fr: 'Agritourisme', de: 'Bauernhof', es: 'Agroturismo',
      pt: 'Agroturismo', nl: 'Boerderij', pl: 'Agroturystyka', ru: 'Агротуризм', sv: 'Bondgård',
      zh: '农家乐', ja: '農家民宿', ko: '농촌 민박', th: 'ฟาร์มสเตย์', ar: 'إقامة ريفية',
    },
  },
  {
    id: 'apartment',
    translations: {
      it: 'Casa vacanze', en: 'Apartment', fr: 'Appartement', de: 'Ferienwohnung', es: 'Apartamento',
      pt: 'Apartamento', nl: 'Appartement', pl: 'Apartament', ru: 'Апартаменты', sv: 'Lägenhet',
      zh: '公寓', ja: 'アパートメント', ko: '아파트', th: 'อพาร์ตเมนต์', ar: 'شقة',
    },
  },
];

const LODGING_MAP = new Map(ACCOMMODATION_CATEGORIES.map(c => [c.id, c]));

/** Label tradotta del tipo struttura per un id (es. 'hotel' → 'Hotel') */
export function getLodgingLabel(id: string, lang: string = 'it'): string {
  const cat = LODGING_MAP.get(id as LodgingTypeId);
  if (!cat) return id;
  return cat.translations[lang as keyof typeof cat.translations] ?? cat.translations.it;
}

/**
 * Icona MaterialCommunityIcons per il "tipo luogo", dalla faccetta lodging.
 * SORGENTE DI VERITÀ: restaurants.offers_lodging. Regola unica (centralizzata qui
 * così la decisione vive in un posto solo): struttura → letto, ristorante →
 * forchetta-coltello. Nota: un hotel-con-ristorante (offers_lodging=true) mostra
 * SEMPRE il letto, coerente con le recensioni unificate (non distinguiamo
 * soggiorno vs pasto).
 */
export function venueIconName(offersLodging?: boolean | null): 'bed' | 'silverware-fork-knife' {
  return offersLodging ? 'bed' : 'silverware-fork-knife';
}
