// I nomi degli ALTRI alimenti che un utente può indicare nell'app oltre ai
// 15 allergeni (constants/otherFoods.ts dell'app), solo italiano e inglese.
// Copia gemella come categories.ts e dishNotes.ts: servono alle pill delle
// esigenze nelle recensioni (/recensioni), che altrimenti mostrerebbero il
// codice. ⚠️ Si aggiorna quando l'app aggiunge un alimento; un codice che
// manca qui ricade su una versione leggibile del codice stesso.
//
// ⚠️ SOLO PER LEGGERE, mai per scegliere (scelta dell'utente, 25/09): non
// sono allergeni obbligatori, e ai piatti del ristoratore si associano solo i
// 15 di allergens.ts. Non usare questa lista nell'editor dei piatti.

export const OTHER_FOOD_NAMES: Record<string, { it: string; en: string }> = {
  tomato: { it: 'Pomodoro', en: 'Tomato' },
  onion: { it: 'Cipolla', en: 'Onion' },
  garlic: { it: 'Aglio', en: 'Garlic' },
  chives: { it: 'Erba cipollina', en: 'Chives' },
  bell_pepper: { it: 'Peperone', en: 'Bell pepper' },
  eggplant: { it: 'Melanzana', en: 'Eggplant' },
  carrot: { it: 'Carota', en: 'Carrot' },
  mushrooms: { it: 'Funghi', en: 'Mushrooms' },
  pumpkin: { it: 'Zucca', en: 'Pumpkin' },
  zucchini: { it: 'Zucchina', en: 'Zucchini' },
  cucumber: { it: 'Cetriolo', en: 'Cucumber' },
  fennel: { it: 'Finocchio', en: 'Fennel' },
  asparagus: { it: 'Asparagi', en: 'Asparagus' },
  celeriac: { it: 'Sedano rapa', en: 'Celeriac' },
  spinach: { it: 'Spinaci', en: 'Spinach' },
  broccoli: { it: 'Broccoli', en: 'Broccoli' },
  lettuce: { it: 'Lattuga', en: 'Lettuce' },
  potato: { it: 'Patata', en: 'Potato' },
  artichoke: { it: 'Carciofo', en: 'Artichoke' },
  cauliflower: { it: 'Cavolfiore', en: 'Cauliflower' },
  leek: { it: 'Porro', en: 'Leek' },
  cabbage: { it: 'Cavolo', en: 'Cabbage' },
  peach: { it: 'Pesca', en: 'Peach' },
  kiwi: { it: 'Kiwi', en: 'Kiwi' },
  strawberries: { it: 'Fragole', en: 'Strawberries' },
  blueberries: { it: 'Mirtilli', en: 'Blueberries' },
  raspberries: { it: 'Lamponi', en: 'Raspberries' },
  blackberries: { it: 'More', en: 'Blackberries' },
  apple: { it: 'Mela', en: 'Apple' },
  banana: { it: 'Banana', en: 'Banana' },
  cherry: { it: 'Ciliegia', en: 'Cherry' },
  apricot: { it: 'Albicocca', en: 'Apricot' },
  plum: { it: 'Prugna', en: 'Plum' },
  pear: { it: 'Pera', en: 'Pear' },
  citrus: { it: 'Agrumi', en: 'Citrus fruits' },
  coconut: { it: 'Cocco', en: 'Coconut' },
  pineapple: { it: 'Ananas', en: 'Pineapple' },
  mango: { it: 'Mango', en: 'Mango' },
  papaya: { it: 'Papaya', en: 'Papaya' },
  avocado: { it: 'Avocado', en: 'Avocado' },
  grapes: { it: 'Uva', en: 'Grapes' },
  melon: { it: 'Melone', en: 'Melon' },
  watermelon: { it: 'Anguria', en: 'Watermelon' },
  fig: { it: 'Fico', en: 'Fig' },
  passion_fruit: { it: 'Frutto della passione', en: 'Passion fruit' },
  pomegranate: { it: 'Melograno', en: 'Pomegranate' },
  chickpeas: { it: 'Ceci', en: 'Chickpeas' },
  lentils: { it: 'Lenticchie', en: 'Lentils' },
  beans: { it: 'Fagioli', en: 'Beans' },
  peas: { it: 'Piselli', en: 'Peas' },
  corn: { it: 'Mais', en: 'Corn' },
  buckwheat: { it: 'Grano saraceno', en: 'Buckwheat' },
  rice: { it: 'Riso', en: 'Rice' },
  oats: { it: 'Avena', en: 'Oats' },
  wheat: { it: 'Frumento', en: 'Wheat' },
  barley: { it: 'Orzo', en: 'Barley' },
  rye: { it: 'Segale', en: 'Rye' },
  spelt: { it: 'Farro', en: 'Spelt' },
  pepper: { it: 'Pepe', en: 'Pepper' },
  nutmeg: { it: 'Noce moscata', en: 'Nutmeg' },
  turmeric: { it: 'Curcuma', en: 'Turmeric' },
  coriander: { it: 'Coriandolo', en: 'Coriander' },
  spicy: { it: 'Spezie piccanti', en: 'Spicy foods' },
  cinnamon: { it: 'Cannella', en: 'Cinnamon' },
  ginger: { it: 'Zenzero', en: 'Ginger' },
  chamomile: { it: 'Camomilla', en: 'Chamomile' },
  basil: { it: 'Basilico', en: 'Basil' },
  sage: { it: 'Salvia', en: 'Sage' },
  mint: { it: 'Menta', en: 'Mint' },
  oregano: { it: 'Origano', en: 'Oregano' },
  rosemary: { it: 'Rosmarino', en: 'Rosemary' },
  cumin: { it: 'Cumino', en: 'Cumin' },
  paprika: { it: 'Paprika', en: 'Paprika' },
  almonds: { it: 'Mandorle', en: 'Almonds' },
  hazelnuts: { it: 'Nocciole', en: 'Hazelnuts' },
  walnuts: { it: 'Noci', en: 'Walnuts' },
  pistachios: { it: 'Pistacchi', en: 'Pistachios' },
  cashews: { it: 'Anacardi', en: 'Cashews' },
  pine_nuts: { it: 'Pinoli', en: 'Pine nuts' },
  chestnuts: { it: 'Castagne', en: 'Chestnuts' },
  pecan: { it: 'Noce pecan', en: 'Pecan' },
  brazil_nut: { it: 'Noce del Brasile', en: 'Brazil nut' },
  macadamia: { it: 'Macadamia', en: 'Macadamia' },
  poppy_seeds: { it: 'Semi di papavero', en: 'Poppy seeds' },
  sunflower_seeds: { it: 'Semi di girasole', en: 'Sunflower seeds' },
  flax_seeds: { it: 'Semi di lino', en: 'Flax seeds' },
  cacao_chocolate: { it: 'Cacao/Cioccolato', en: 'Cacao/Chocolate' },
  honey: { it: 'Miele', en: 'Honey' },
  olive_oil: { it: 'Olio d\'oliva', en: 'Olive oil' },
  coffee: { it: 'Caffè', en: 'Coffee' },
  tea: { it: 'Tè', en: 'Tea' },
  yeast: { it: 'Lievito', en: 'Yeast' },
  artificial_colorings: { it: 'Coloranti artificiali', en: 'Artificial colorings' },
  pork: { it: 'Carne di maiale', en: 'Pork' },
  red_meat: { it: 'Carne rossa', en: 'Red meat' },
  chicken: { it: 'Pollo', en: 'Chicken' },
  snails: { it: 'Lumache', en: 'Snails' },
};

export function otherFoodName(code: string, locale: 'it' | 'en'): string | null {
  return OTHER_FOOD_NAMES[code]?.[locale] ?? null;
}
